const fs = require("fs");

const path = "data/manual_drops/architecture_milestones/architecture_milestones_2008_2026.json";
const doc = JSON.parse(fs.readFileSync(path, "utf8"));

const retrievedAt = "2026-05-17";

const records = [
  {
    city_id: "london",
    event_id: "lon_arch_415_wick_lane_completion_2025",
    date: "2025-01-01",
    bucket: "planning/development/architecture/mixed-use housing",
    title: "415 Wick Lane was listed as built",
    summary: "NLA records 415 Wick Lane as a built co-location and mixed-use scheme in Hackney Wick, with 175 homes and commercial space, and completion in 2025.",
    observed_change: "A mixed-use housing and workspace scheme was recorded as completed at 415 Wick Lane.",
    area: "415 Wick Lane, Hackney Wick",
    latitude: 51.5362,
    longitude: -0.0235,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: 415 Wick Lane",
    source_url: "https://nla.london/projects/415-wick-lane",
    source_record_id: "nla-415-wick-lane",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "dRMM with Taylor Wimpey London and project team",
    project_type: "mixed-use housing and commercial workspace",
    geometry_source: "Approximate point geocoded from project name and NLA borough context.",
    geometry_precision: "site",
    limitations: "Source is a curated project page, not a planning register entry. Year-only completion is represented as the first day of the stated year."
  },
  {
    city_id: "london",
    event_id: "lon_arch_kidbrooke_park_road_north_completion_2024",
    date: "2024-01-01",
    bucket: "planning/development/architecture/housing",
    title: "Kidbrooke Park Road North was listed as built",
    summary: "NLA records Kidbrooke Park Road North as a built Greenwich Builds housing scheme delivering 122 affordable homes, a nursery, and a community hub, with completion in 2024.",
    observed_change: "A civic-led housing scheme with nursery and community facilities was recorded as completed on the former RAF Kidbrooke / Thomas Tallis School site.",
    area: "Kidbrooke Park Road North, Greenwich",
    latitude: 51.4636,
    longitude: 0.0349,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Kidbrooke Park Road North",
    source_url: "https://nla.london/projects/kidbrooke-park-road-north",
    source_record_id: "nla-kidbrooke-park-road-north",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "HTA Design with Durkan, Greenwich Builds, and Royal Borough of Greenwich",
    project_type: "affordable housing and community facilities",
    geometry_source: "Approximate point geocoded from project name and NLA borough context.",
    geometry_precision: "site",
    limitations: "Source is a curated awards/project page. Date is year-level and does not separate handover, occupation, or later phases."
  },
  {
    city_id: "london",
    event_id: "lon_arch_cockpit_deptford_retrofit_completion_2024",
    date: "2024-01-01",
    bucket: "planning/development/architecture/cultural workspace",
    title: "Cockpit Deptford retrofit was listed as built",
    summary: "NLA records Cockpit Deptford as a built retrofit of a craft centre in Lewisham, with public-facing amenities, studio expansion, and completion in 2024.",
    observed_change: "A craft production centre was recorded as retrofitted with new public-facing, workshop, garden, and studio facilities.",
    area: "Cockpit Deptford, Creekside",
    latitude: 51.4807,
    longitude: -0.0256,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Cockpit Deptford",
    source_url: "https://nla.london/projects/cockpit-deptford",
    source_record_id: "nla-cockpit-deptford",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Cooke Fawcett Architects with Cockpit Studios and project team",
    project_type: "creative workspace retrofit",
    geometry_source: "Approximate point geocoded from Cockpit Deptford / Creekside location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Date is year-level; individual studio occupation and public programme dates may differ."
  },
  {
    city_id: "london",
    event_id: "lon_arch_469_bethnal_green_road_retrofit_completion_2025",
    date: "2025-01-01",
    bucket: "planning/development/architecture/workspace retrofit",
    title: "469 Bethnal Green Road was listed as built",
    summary: "NLA records 469 Bethnal Green Road as a built deep retrofit of a former textile workshop into contemporary flexible workspace, with completion in 2025.",
    observed_change: "A former textile-workshop building was recorded as retained, extended, and reused as flexible workspace.",
    area: "469 Bethnal Green Road, Tower Hamlets",
    latitude: 51.5254,
    longitude: -0.0609,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: 469 Bethnal Green Road",
    source_url: "https://nla.london/projects/469-bethnal-green-road",
    source_record_id: "nla-469-bethnal-green-road",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Carmody Groarke with Unity and project team",
    project_type: "workspace retrofit and extension",
    geometry_source: "Approximate point geocoded from named street address.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. The coordinate follows the named project address; NLA page location metadata should be reviewed before parcel-level reuse."
  },
  {
    city_id: "london",
    event_id: "lon_arch_point_blank_hoxton_completion_2024",
    date: "2024-09-01",
    bucket: "planning/development/architecture/education retrofit",
    title: "Point Blank Hoxton campus expansion was listed as built",
    summary: "NLA records Point Blank as a built campus expansion at 13 Penn Street, transforming a Victorian warehouse into a music education facility, with estimated completion in September 2024.",
    observed_change: "A Victorian warehouse was recorded as restored and fitted out for expanded music education use.",
    area: "13 Penn Street, Hoxton",
    latitude: 51.5308,
    longitude: -0.0841,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Point Blank",
    source_url: "https://nla.london/projects/point-blank",
    source_record_id: "nla-point-blank",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "LOM architecture and design",
    project_type: "education retrofit and fit-out",
    geometry_source: "Approximate point geocoded from NLA location field.",
    geometry_precision: "site",
    limitations: "Source is a curated project page and uses an estimated completion month; final occupation or teaching start dates may differ."
  },
  {
    city_id: "london",
    event_id: "lon_arch_paradise_se11_office_completion_2025",
    date: "2025-01-01",
    bucket: "planning/development/architecture/office",
    title: "Paradise SE11 was listed as built",
    summary: "NLA records Paradise SE11 as a built workplace project beside Old Paradise Gardens in Lambeth, with completion in 2025.",
    observed_change: "A six-storey workplace building was recorded as completed beside Old Paradise Gardens.",
    area: "Old Paradise Gardens / Paradise Street, Lambeth",
    latitude: 51.4944,
    longitude: -0.1185,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Paradise SE11",
    source_url: "https://www.nla.london/projects/paradise-se11",
    source_record_id: "nla-paradise-se11",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Feilden Clegg Bradley Studios with Bywater Properties and project team",
    project_type: "office development",
    geometry_source: "Approximate point geocoded from project description beside Old Paradise Gardens.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Date is year-level and does not identify tenant fit-out or opening dates."
  },
  {
    city_id: "london",
    event_id: "lon_arch_granada_cinema_walthamstow_restoration_completion_2025",
    date: "2025-01-01",
    bucket: "planning/development/architecture/conservation",
    title: "Former Granada Cinema restoration was listed as built",
    summary: "NLA records the Grade II* listed former Granada Cinema building in Walthamstow as a built restoration and theatre conversion, with completion in 2025.",
    observed_change: "A listed former cinema building was recorded as restored and modernised for cultural use.",
    area: "Former Granada Cinema, Walthamstow",
    latitude: 51.5844,
    longitude: -0.0191,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: The Grade II* Listed Former Granada Cinema Building",
    source_url: "https://nla.london/projects/the-grade-ii-listed-former-granada-cinema-building",
    source_record_id: "nla-former-granada-cinema-walthamstow",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Bond Bryan and Pilbrow & Partners with London Borough of Waltham Forest and project team",
    project_type: "listed theatre restoration and adaptive reuse",
    geometry_source: "Approximate point geocoded from Walthamstow former Granada Cinema location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Date is year-level and does not distinguish restoration completion from public theatre opening."
  },
  {
    city_id: "london",
    event_id: "lon_arch_huddle_wimbledon_fire_station_completion_2025",
    date: "2025-01-01",
    bucket: "planning/development/architecture/workspace retrofit",
    title: "Huddle Wimbledon Fire Station was listed as built",
    summary: "NLA records Huddle Wimbledon Fire Station as a built reuse of a Grade II listed fire station near Wimbledon station, with completion in 2025.",
    observed_change: "A listed former fire-station building was recorded as reused for workspace and hospitality-led public access.",
    area: "4 Queen's Road, Wimbledon",
    latitude: 51.4218,
    longitude: -0.2059,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Huddle Wimbledon Fire Station",
    source_url: "https://nla.london/projects/huddle-wimbledon-fire-station",
    source_record_id: "nla-huddle-wimbledon-fire-station",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Studio YUME with Romulus and project team",
    project_type: "listed building retrofit and workspace reuse",
    geometry_source: "Approximate point geocoded from NLA location field.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Date is year-level and does not identify tenancy or phased fit-out dates."
  },
  {
    city_id: "london",
    event_id: "lon_arch_highgate_newtown_community_partners_completion_2020",
    date: "2020-01-01",
    bucket: "planning/development/architecture/community housing",
    title: "Highgate Newtown Community Partners scheme was listed as built",
    summary: "NLA records Highgate Newtown Community Partners as a built Camden housing and community scheme, with completion in 2020.",
    observed_change: "A community-led housing and neighbourhood facility scheme was recorded as completed in Highgate Newtown.",
    area: "Highgate Newtown, Camden",
    latitude: 51.5552,
    longitude: -0.1438,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Highgate Newtown Community Partners",
    source_url: "https://nla.london/projects/highgate-newtown-community-centre",
    source_record_id: "nla-highgate-newtown-community-centre",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "RCKa, Hunters, Camden Council, and project team",
    project_type: "housing and community centre",
    geometry_source: "Approximate point geocoded from Highgate Newtown Community Partners location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Date is year-level and does not separate construction completion from occupation or community-programme dates."
  },
  {
    city_id: "london",
    event_id: "lon_arch_brent_cross_town_conductor_house_completion_2025",
    date: "2025-03-01",
    bucket: "planning/development/architecture/regeneration housing",
    title: "Brent Cross Town Conductor House homes were listed as completed",
    summary: "NLA records Brent Cross Town as built and states that Conductor House was completed in March 2025 with 120 new homes, including replacement social housing for Whitefield Estate secure tenants.",
    observed_change: "An early housing block in the Brent Cross Town regeneration area was recorded as completed and ready for residents.",
    area: "Brent Cross Town / Whitefield Estate",
    latitude: 51.5723,
    longitude: -0.2227,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Brent Cross Town",
    source_url: "https://nla.london/projects/brent-cross-town-11",
    source_record_id: "nla-brent-cross-town-conductor-house",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA narrative completion month for Conductor House",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Allies and Morrison, Squires, Maccreanor Lavington, ShedKM, WCA, Makower Architects, Related Argent, Barnet Council, and project team",
    project_type: "regeneration housing phase",
    geometry_source: "Approximate point geocoded from Brent Cross Town / Whitefield Estate area.",
    geometry_precision: "neighbourhood",
    limitations: "Source is a curated project page about the wider Brent Cross Town programme. This record isolates the Conductor House completion mentioned in the page narrative; wider neighbourhood phases have separate dates."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_selmas_house_renovation_start_2025",
    date: "2025-03-06",
    bucket: "planning/development/architecture/cultural facility",
    title: "Selma's House renovation was announced",
    summary: "NYC DDC announced a funded renovation of Selma's House at the Louis Armstrong House Museum campus in Corona, Queens, to restore and upgrade the building and exterior access.",
    observed_change: "A museum-campus support building was recorded as entering a renovation programme for office, meeting, storage, kitchen, building-systems, and ADA access upgrades.",
    area: "34-52 107th Street, Corona, Queens",
    latitude: 40.7548,
    longitude: -73.8617,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Selma's House renovation",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2025/pr-030625-LouisArmstrong.page",
    source_record_id: "nyc-ddc-pr-030625-louis-armstrong-selmas-house",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "CTA Architects with NYC DDC, NYC DCLA, and Louis Armstrong House Museum",
    project_type: "historic cultural-campus building renovation",
    geometry_source: "Approximate point geocoded from DDC-stated address.",
    geometry_precision: "site",
    limitations: "The event records the public announcement / project start, not completion. Final works, opening, and operating changes require later source records."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_flatbush_avenue_plaza_renovation_completion_2024",
    date: "2024-11-01",
    bucket: "planning/development/public realm/infrastructure",
    title: "Flatbush Avenue plaza and Park Slope infrastructure project completed",
    summary: "NYC DDC announced completion of a Park Slope infrastructure project that replaced water mains, upgraded combined sewers, and renovated the 8th Avenue Triangle / Flatbush Avenue public space.",
    observed_change: "Water, sewer, sidewalk, ramp, and plaza upgrades were recorded as completed near Flatbush Avenue and Grand Army Plaza.",
    area: "8th Avenue Triangle / Flatbush Avenue, Park Slope",
    latitude: 40.6746,
    longitude: -73.9696,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Park Slope / Flatbush Avenue Plaza",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-110124-ParkSlope.page",
    source_record_id: "nyc-ddc-pr-110124-parkslope-flatbush-avenue-plaza",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC, NYC DEP, NYC DOT, and project team",
    project_type: "street infrastructure and public-realm upgrade",
    geometry_source: "Approximate point geocoded from DDC-stated Flatbush Avenue / 8th Avenue Triangle location.",
    geometry_precision: "site",
    limitations: "The event combines plaza and utility works from the same DDC project announcement; it is not a parcel-level building record."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_osborn_street_plaza_design_award_2024",
    date: "2024-01-25",
    bucket: "planning/development/public realm/plaza",
    title: "Osborn Street Plaza project received Envision verification",
    summary: "NYC DDC and NYC DOT announced that the planned Osborn Street Plaza in Brownsville received an Envision Verified Award and that construction was expected to start in March 2024.",
    observed_change: "A dead-end street segment beside Langston Hughes Houses was documented as a plaza project with shaded seating, planting, bioswales, and pedestrian access.",
    area: "Osborn Street south of Belmont Avenue, Brownsville",
    latitude: 40.668,
    longitude: -73.908,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Osborn Street Plaza",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-012524-OsbornStPlaza.page",
    source_record_id: "nyc-ddc-pr-012524-osborn-street-plaza",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC, NYC DOT, Brownsville Community Justice Center, and project team",
    project_type: "planned pedestrian plaza and public realm",
    geometry_source: "Approximate point geocoded from DDC-stated Osborn Street / Belmont Avenue location.",
    geometry_precision: "block",
    limitations: "The event records award/design and construction-start announcement, not completed public opening. Later completion should be recorded separately."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_70_mulberry_public_art_approval_2024",
    date: "2024-01-16",
    bucket: "planning/development/architecture/public art",
    title: "70 Mulberry public artwork concept was approved",
    summary: "NYC DDC and DCLA announced Public Design Commission conceptual approval for Jennifer Wen Ma's Wings of Everchange public artwork for the new 70 Mulberry building in Chinatown.",
    observed_change: "A permanent public-art component for the 70 Mulberry reconstruction was recorded as approved for conceptual design.",
    area: "70 Mulberry Street, Chinatown",
    latitude: 40.7156,
    longitude: -73.9995,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: 70 Mulberry public art",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-011624-70Mulberry.page",
    source_record_id: "nyc-ddc-pr-011624-70-mulberry-wings-of-everchange",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "Jennifer Wen Ma, NYC DCLA Percent for Art, NYC DDC, and 70 Mulberry project team",
    project_type: "public art approval for civic building reconstruction",
    geometry_source: "Approximate point geocoded from stated building address.",
    geometry_precision: "site",
    limitations: "The event records conceptual approval for public art within a reconstruction project, not installation or building completion."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_jefferson_market_library_reopening_2022",
    date: "2022-07-14",
    bucket: "planning/development/architecture/library conservation",
    title: "Jefferson Market Library reopened after accessibility upgrades",
    summary: "NYPL reported the reopening of the historic Jefferson Market branch after a capital project that added accessibility and interior upgrades to the landmark building.",
    observed_change: "A landmark library building was recorded as reopened after entrance, elevator, restroom, public-space, and building-access upgrades.",
    area: "Jefferson Market Library, Greenwich Village",
    latitude: 40.734,
    longitude: -74.0007,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "New York Public Library press release: Jefferson Market branch reopening",
    source_url: "https://www.nypl.org/press/new-york-public-librarys-jefferson-market-branch-reopens-following-significant-improvements",
    source_record_id: "nypl-jefferson-market-branch-reopening-2022",
    source_retrieved_at: retrievedAt,
    source_date_field: "NYPL press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "WXY Architecture + Urban Design with NYC DDC, NYPL, and project team",
    project_type: "historic library renovation and accessibility upgrade",
    geometry_source: "Approximate point geocoded from known branch location.",
    geometry_precision: "site",
    limitations: "The event records branch reopening after the capital project; construction phases and detailed landmark approvals are separate evidence paths."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_city_island_water_connection_completion_2022",
    date: "2022-07-20",
    bucket: "planning/development/infrastructure/water",
    title: "City Island drinking-water connection completed",
    summary: "NYC DDC announced completion of a new drinking-water connection to City Island, including two 20-inch subaqueous water mains under Eastchester Bay.",
    observed_change: "A subaqueous water-main connection was recorded as completed between the mainland and City Island.",
    area: "City Island / Eastchester Bay, Bronx",
    latitude: 40.8468,
    longitude: -73.7868,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: City Island water connection",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2022/pr-072022-CityIsland.page",
    source_record_id: "nyc-ddc-pr-072022-city-island-water-connection",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "Dewberry, Northeast Remsco Construction, McMillen Jacobs Associates, NYC DEP, and NYC DDC",
    project_type: "subaqueous water infrastructure",
    geometry_source: "Approximate point geocoded from City Island / Eastchester Bay project area.",
    geometry_precision: "neighbourhood",
    limitations: "The event records infrastructure completion at project-area precision; it is not a mapped alignment of the subaqueous mains."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_shore_road_douglaston_stabilization_completion_2022",
    date: "2022-06-23",
    bucket: "planning/development/infrastructure/coastal roadway",
    title: "Shore Road stabilization in Douglaston completed",
    summary: "NYC DDC announced completion of an emergency contract to stabilize Shore Road from West Drive to Bayview Avenue along Little Neck Bay in Douglaston.",
    observed_change: "A coastal roadway and embankment stabilization project was recorded as completed with gabion baskets, support works, restored walkway, and roadway repairs.",
    area: "Shore Road, Douglaston",
    latitude: 40.7968,
    longitude: -73.7474,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Shore Road stabilization",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2022/pr-062322-ShoreRoad.page",
    source_record_id: "nyc-ddc-pr-062322-shore-road-douglaston",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC in-house design team, Hazen and Sawyer, MFM Contracting, and EnTech Engineering",
    project_type: "coastal roadway stabilization",
    geometry_source: "Approximate point geocoded from DDC-stated Shore Road / Little Neck Bay project area.",
    geometry_precision: "corridor",
    limitations: "The event records project completion for a road segment; it is not a measured line geometry of the embankment or walkway."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_flushing_infrastructure_upgrade_completion_2018",
    date: "2018-03-28",
    bucket: "planning/development/infrastructure/street and utilities",
    title: "Flushing infrastructure upgrade completed",
    summary: "NYC DEP and DDC announced completion of a USD 71 million infrastructure upgrade in Flushing, Queens, including storm sewers, sanitary sewers, water mains, hydrants, catch basins, repaving, sidewalks, lighting, signals, pedestrian ramps, and new trees.",
    observed_change: "A multi-street drainage, water-main, roadway, sidewalk, lighting, signal, ramp, and planting upgrade was recorded as completed in the Flushing project area.",
    area: "Flushing, Queens",
    latitude: 40.7627,
    longitude: -73.8357,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Flushing infrastructure upgrade",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2018/pr-032818-million-infrastructure-upgrade-flushing.page",
    source_record_id: "nyc-ddc-pr-032818-flushing-infrastructure-upgrade",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DDC, and project team",
    project_type: "street, sewer, water-main, and public-realm infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated Flushing project area.",
    geometry_precision: "neighbourhood",
    limitations: "The event records project completion at neighbourhood precision. It does not map each sewer, water-main, sidewalk, signal, ramp, or tree location."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_queens_borough_hall_parking_lot_opening_2018",
    date: "2018-03-26",
    bucket: "planning/development/civic infrastructure/parking and public realm",
    title: "Queens Borough Hall municipal parking lot opened",
    summary: "NYC DDC announced that the new municipal parking lot at Queens Borough Hall had opened after a USD 8.8 million construction project for NYC DOT.",
    observed_change: "A former parking-garage site was recorded as reopened as a surface municipal lot with more than 300 spaces, stormwater management, rain gardens, seating areas, bike parking, EV charging, ADA access, lighting, fencing, retaining walls, and planting.",
    area: "Queens Borough Hall, Kew Gardens",
    latitude: 40.7138,
    longitude: -73.8289,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Queens Borough Hall parking lot",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2018/pr-032618-parking-lot-queens.page",
    source_record_id: "nyc-ddc-pr-032618-queens-borough-hall-parking-lot",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "WXY Studios, Tully Construction, NYC DOT, and NYC DDC",
    project_type: "municipal parking lot and civic-site public realm",
    geometry_source: "Approximate point geocoded from DDC-stated Queens Borough Hall parking lot bounds.",
    geometry_precision: "site",
    limitations: "The event records opening of the municipal parking lot. It is distinct from nearby Queens Borough Hall plaza records and does not map individual spaces, planting beds, or stormwater assets."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_lucas_street_sewers_completion_2018",
    date: "2018-03-07",
    bucket: "planning/development/infrastructure/sewer and street",
    title: "Lucas Street sewer upgrade in St. Albans neared completion",
    summary: "NYC DDC announced that a USD 21.8 million infrastructure project around Lucas Street in St. Albans had brought expanded storm sewers, new sanitary sewers, new water mains, catch basins, curb repairs, and related street works to the area.",
    observed_change: "A Southeast Queens drainage and utility upgrade was recorded as substantially installed around Lucas Street, including storm sewers, sanitary sewers, water mains, catch basins, and curb repairs.",
    area: "Lucas Street, St. Albans",
    latitude: 40.6936,
    longitude: -73.7605,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Lucas Street sewer project",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2018/pr-030718-southeast-queens-sewer-project.page",
    source_record_id: "nyc-ddc-pr-030718-lucas-street-sewer-project",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DDC, Inter Contracting, LaPeruta Construction Corporation, and project team",
    project_type: "sewer, water-main, and street infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated Lucas Street / St. Albans project area.",
    geometry_precision: "corridor",
    limitations: "The press release states the project was on track to finish early and that major infrastructure had been brought to the area; this record treats the date as a documented substantial-installation milestone, not a final closeout certificate."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_maple_leaf_club_housing_reapproved_2025",
    date: "2025-02-11",
    bucket: "planning/development/architecture/housing",
    title: "Former Maple Leaf Club housing applications were re-approved",
    summary: "Belfast Planning Committee re-approved two linked applications for social and affordable housing at the former Maple Leaf Club, 41-43 Park Avenue, subject to conditions and a Section 76 planning agreement.",
    observed_change: "A documented planning decision kept apartment and dwelling proposals for the former Maple Leaf Club site live, with planning obligations tied to affordable housing, public open-space works, and a pocket park.",
    area: "Former Maple Leaf Club, 41-43 Park Avenue",
    latitude: 54.5968,
    longitude: -5.876,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 11 February 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MID=12038",
    source_record_id: "bcc-planning-2025-02-11-maple-leaf-club-la04-2019-0081-la04-2020-2325",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "social and affordable housing planning approval",
    geometry_source: "Approximate point geocoded from committee-stated former Maple Leaf Club / Park Avenue location.",
    geometry_precision: "site",
    limitations: "The event records committee re-approval subject to a planning agreement deadline. It does not confirm that the agreement issued, construction started, or homes were delivered."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_woodcot_avenue_hmo_refused_2025",
    date: "2025-02-11",
    bucket: "planning/development/architecture/housing decision",
    title: "49 Woodcot Avenue HMO application was refused",
    summary: "Belfast Planning Committee refused an application to change 49 Woodcot Avenue from a four-bedroom dwelling to a four-bedroom HMO.",
    observed_change: "A documented planning refusal was recorded for a proposed HMO conversion at 49 Woodcot Avenue.",
    area: "49 Woodcot Avenue",
    latitude: 54.583,
    longitude: -5.869,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee agenda item: 49 Woodcot Avenue",
    source_url: "https://minutes.belfastcity.gov.uk/mgAi.aspx?ID=82040",
    source_record_id: "bcc-planning-2025-02-11-woodcot-avenue-la04-2024-1623",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Create Architecture named as speaker for applicant in minutes",
    project_type: "HMO conversion refusal",
    geometry_source: "Approximate point geocoded from committee-stated street address.",
    geometry_precision: "site",
    limitations: "The event records the committee decision only; subsequent appeals, revised submissions, or licensing decisions require separate source records."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_divis_black_mountain_visitor_facilities_approved_2025",
    date: "2025-02-11",
    bucket: "planning/development/architecture/visitor facilities",
    title: "Divis and Black Mountain visitor facilities were approved",
    summary: "Belfast Planning Committee granted planning permission for visitor-site alterations at the Divis and The Black Mountain National Trust site, including repurposed vernacular buildings, an amenity building, signage, paths, and pond-network enhancements.",
    observed_change: "Visitor-facility, landscape, and access improvements were recorded as approved for the Divis and Black Mountain National Trust site.",
    area: "Divis and The Black Mountain National Trust Site, Divis Road",
    latitude: 54.6,
    longitude: -6.014,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 11 February 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MID=12038",
    source_record_id: "bcc-planning-2025-02-11-divis-black-mountain-la04-2024-1458",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "The Paul Hogarth Company and National Trust project team",
    project_type: "visitor facilities and landscape planning approval",
    geometry_source: "Approximate point geocoded from committee-stated National Trust site and Divis Road location.",
    geometry_precision: "site",
    limitations: "The event records planning permission with delegated handling of outstanding consultation responses; construction, opening, and final landscape delivery are separate evidence paths."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_cathedral_gardens_public_realm_approved_2025",
    date: "2025-02-11",
    bucket: "planning/development/public realm",
    title: "Cathedral Gardens public-realm improvement was approved",
    summary: "Belfast Planning Committee granted planning permission for a public-realm environmental improvement scheme at Cathedral Gardens / Buoy Park, Donegall Street.",
    observed_change: "A documented planning approval was recorded for public-realm and landscape works at Cathedral Gardens.",
    area: "Cathedral Gardens / Buoy Park, Donegall Street",
    latitude: 54.604,
    longitude: -5.927,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 11 February 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MID=12038",
    source_record_id: "bcc-planning-2025-02-11-cathedral-gardens-la04-2024-1551",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "public-realm planning approval",
    geometry_source: "Approximate point geocoded from committee-stated Cathedral Gardens / Donegall Street location.",
    geometry_precision: "site",
    limitations: "The event records the 2025 planning approval and is distinct from earlier interim public access. Delivery, opening, maintenance, and final design details require separate records."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_annadale_avenue_residential_refused_2025",
    date: "2025-08-12",
    bucket: "planning/development/architecture/housing decision",
    title: "18 Annadale Avenue residential redevelopment was refused",
    summary: "Belfast Planning Committee refused permission for demolition of the existing building at 18 Annadale Avenue and construction of a 14-unit residential development.",
    observed_change: "A documented planning refusal was recorded for a proposed demolition and apartment / terraced-dwelling scheme at 18 Annadale Avenue.",
    area: "18 Annadale Avenue",
    latitude: 54.5716,
    longitude: -5.9176,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee agenda item: 18 Annadale Avenue",
    source_url: "https://minutes.belfastcity.gov.uk/mgAi.aspx?ID=84252",
    source_record_id: "bcc-planning-2025-08-12-annadale-avenue-la04-2022-1046",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant design team not named in minutes extract",
    project_type: "residential redevelopment refusal",
    geometry_source: "Approximate point geocoded from committee-stated street address.",
    geometry_precision: "site",
    limitations: "The event records committee refusal only. Reasons were delegated to officers; appeal, resubmission, or lawful demolition status must be checked separately."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_rosetta_road_hmo_retail_refused_2025",
    date: "2025-08-12",
    bucket: "planning/development/architecture/housing decision",
    title: "41 Rosetta Road HMO and retail alterations were refused",
    summary: "Belfast Planning Committee refused an application for ground-floor retail alterations and upper-floor HMO use at 41 Rosetta Road.",
    observed_change: "A documented planning refusal was recorded for retail extension, rear extension, dormer, and six-person HMO works at 41 Rosetta Road.",
    area: "41 Rosetta Road",
    latitude: 54.5633,
    longitude: -5.9042,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee agenda item: 41 Rosetta Road",
    source_url: "https://minutes.belfastcity.gov.uk/mgAi.aspx?ID=84253",
    source_record_id: "bcc-planning-2025-08-12-rosetta-road-la04-2024-1466",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "mixed retail and HMO refusal",
    geometry_source: "Approximate point geocoded from committee-stated street address.",
    geometry_precision: "site",
    limitations: "The event records committee refusal only. The minutes record objections and committee rationale; later appeal or revised submission status is not included."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_432_falls_road_hmo_refused_2025",
    date: "2025-08-12",
    bucket: "planning/development/architecture/housing decision",
    title: "432 Falls Road HMO application was refused",
    summary: "Belfast Planning Committee refused an application to change 432 Falls Road from a seven-bedroom dwelling house to a seven-bedroom / nine-person HMO.",
    observed_change: "A documented planning refusal was recorded for a proposed HMO conversion at 432 Falls Road.",
    area: "432 Falls Road",
    latitude: 54.5886,
    longitude: -5.9847,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 12 August 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=12049",
    source_record_id: "bcc-planning-2025-08-12-432-falls-road-la04-2024-1654",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "HMO conversion refusal",
    geometry_source: "Approximate point geocoded from committee-stated street address.",
    geometry_precision: "site",
    limitations: "The event records committee refusal only. It does not confirm appeal, enforcement, licensing, or revised application outcomes."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_squires_hill_three_dwellings_approved_2025",
    date: "2025-08-12",
    bucket: "planning/development/architecture/housing",
    title: "Squires Hill Road outline housing application was approved",
    summary: "Belfast Planning Committee granted outline permission for three detached dwellings on land between Squires View and Squires Hill Road.",
    observed_change: "A documented outline planning approval was recorded for a small residential infill scheme near Squires Hill Road.",
    area: "Land between No. 22 Squires View and Nos. 57 and 59 Squires Hill Road",
    latitude: 54.6292,
    longitude: -5.964,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee agenda item: Squires Hill Road",
    source_url: "https://minutes.belfastcity.gov.uk/mgAi.aspx?ID=84256",
    source_record_id: "bcc-planning-2025-08-12-squires-hill-road-la04-2024-1865",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "MBA Planning named as agent in minutes; architect not otherwise named",
    project_type: "outline residential planning approval",
    geometry_source: "Approximate point geocoded from committee-stated Squires View / Squires Hill Road location.",
    geometry_precision: "site",
    limitations: "The event records outline permission only. Reserved matters, detailed design, construction, and occupation require later source records."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_34_36_the_mount_housing_approved_2025",
    date: "2025-09-16",
    bucket: "planning/development/architecture/housing conservation",
    title: "34-36 The Mount listed-building housing redevelopment was approved",
    summary: "Belfast Planning Committee granted permission for redevelopment of listed buildings and rear lands at 34-36 The Mount into 20 townhouses and 6 apartments, subject to conditions and a Section 76 planning agreement.",
    observed_change: "A documented planning approval was recorded for a residential scheme involving listed-building renovation and new housing at The Mount.",
    area: "34-36 The Mount",
    latitude: 54.5931,
    longitude: -5.8837,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 16 September 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=12051",
    source_record_id: "bcc-planning-2025-09-16-the-mount-la04-2024-0948",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "MBA Planning named as agent in minutes; design team not otherwise named",
    project_type: "listed-building residential redevelopment approval",
    geometry_source: "Approximate point geocoded from committee-stated 34-36 The Mount location.",
    geometry_precision: "site",
    limitations: "The event records committee planning approval subject to conditions and agreement. Construction start, conservation works, and completion require separate records."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_35_39_royal_avenue_shopfront_consent_2025",
    date: "2025-09-16",
    bucket: "planning/development/architecture/conservation",
    title: "35-39 Royal Avenue shopfront works were approved",
    summary: "Belfast Planning Committee approved full and listed building consent for alterations to the shopfront at 35-39 Royal Avenue.",
    observed_change: "A documented full and listed-building consent decision was recorded for shopfront alterations in the Belfast city centre conservation area.",
    area: "35-39 Royal Avenue",
    latitude: 54.6028,
    longitude: -5.9278,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 16 September 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=12051",
    source_record_id: "bcc-planning-2025-09-16-35-39-royal-avenue-la04-2025-1140-la04-2025-0976",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "shopfront and listed-building consent",
    geometry_source: "Approximate point geocoded from committee-stated Royal Avenue address.",
    geometry_precision: "site",
    limitations: "The event records consent for alterations, not physical completion. Detailed drawings, tenancy, and later facade works require separate evidence."
  }
];

const existingIds = new Set(doc.events.map((event) => event.event_id));
const duplicateIds = records.filter((event) => existingIds.has(event.event_id)).map((event) => event.event_id);
if (duplicateIds.length > 0) {
  throw new Error(`Duplicate event_id values: ${duplicateIds.join(", ")}`);
}

doc.events.push(...records);
doc.sources = doc.sources.map((source) => {
  if (
    source.source_id === "london-architecture-public-pages" ||
    source.source_id === "nyc-architecture-public-pages" ||
    source.source_id === "belfast-architecture-public-pages"
  ) {
    return {
      ...source,
      retrieved_at: retrievedAt
    };
  }
  return source;
});

fs.writeFileSync(path, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`Appended ${records.length} records to ${path}`);
