const fs = require("fs");

const path = "data/manual_drops/architecture_milestones/architecture_milestones_2008_2026.json";
const doc = JSON.parse(fs.readFileSync(path, "utf8"));

const retrievedAt = "2026-05-17";

const records = [
  {
    city_id: "london",
    event_id: "lon_arch_belmont_street_completion_2024",
    date: "2024-01-01",
    bucket: "planning/development/architecture/residential",
    title: "Belmont Street was listed as built",
    summary: "NLA records Belmont Street as a built Camden residential project delivering 115 new homes, 50 percent affordable housing, brick facades, and a green courtyard, with completion in 2024.",
    observed_change: "A Camden residential scheme with new homes, affordable housing, and courtyard landscape was recorded as completed.",
    area: "Belmont Street, Chalk Farm",
    latitude: 51.545,
    longitude: -0.1501,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Belmont Street",
    source_url: "https://nla.london/projects/belmont-street",
    source_record_id: "nla-belmont-street",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "HTA Design LLP, Vistry Group, and project team",
    project_type: "residential development",
    geometry_source: "Approximate point geocoded from NLA-stated Charlie Ratchford Court / Crogsland Road location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Year-only completion is represented as the first day of the stated year; individual occupancy, tenure delivery, and later management require separate evidence."
  },
  {
    city_id: "london",
    event_id: "lon_arch_noele_gordon_house_completion_2024",
    date: "2024-08-01",
    bucket: "planning/development/architecture/affordable later living",
    title: "Noele Gordon House was listed as built",
    summary: "NLA records Noele Gordon House as a built Newham later-living scheme at the Hartley Centre, with 75 affordable homes and an NHS health centre, and estimated completion in August 2024.",
    observed_change: "An East Ham later-living housing and health-centre scheme was recorded as completed.",
    area: "Hartley Centre, 267 Barking Road",
    latitude: 51.532,
    longitude: 0.052,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Noele Gordon House",
    source_url: "https://nla.london/projects/noele-gordon-house-1",
    source_record_id: "nla-noele-gordon-house",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Mae Architects Ltd, London Borough of Newham, Populo Living, Hill Group, and project team",
    project_type: "affordable later-living housing and health centre",
    geometry_source: "Approximate point geocoded from NLA-stated Hartley Centre, 267 Barking Road location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page with an estimated completion month. It documents built status but does not verify occupation, healthcare service start dates, or later management changes."
  },
  {
    city_id: "london",
    event_id: "lon_arch_zodiac_house_retrofit_completion_2025",
    date: "2025-05-01",
    bucket: "planning/development/architecture/residential retrofit",
    title: "Zodiac House retrofit was listed as built",
    summary: "NLA records Zodiac House as a built Croydon retrofit of a 1960s concrete complex into emergency housing, with 73 homes, common space, retail, a repurposed pavilion cafe, and estimated completion in May 2025.",
    observed_change: "A West Croydon concrete office complex was recorded as reused for emergency housing and shared amenities.",
    area: "Zodiac Court, 165 London Road",
    latitude: 51.3797,
    longitude: -0.1044,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Zodiac House",
    source_url: "https://nla.london/projects/zodiac-house-1",
    source_record_id: "nla-zodiac-house",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "shedkm, Common Projects, Planit-IE, ARJ, Whitby Wood, Skelly and Couch, and project team",
    project_type: "adaptive reuse and emergency housing",
    geometry_source: "Approximate point geocoded from NLA-stated Zodiac Court, 165 London Road location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page with an estimated completion month. Housing allocations, support-service operation, and long-term building performance require separate source records."
  },
  {
    city_id: "london",
    event_id: "lon_arch_dockley_apartments_completion_2022",
    date: "2022-08-01",
    bucket: "planning/development/architecture/residential and commercial",
    title: "Dockley Apartments was listed as built",
    summary: "NLA records Dockley Apartments as a built Southwark residential project at 134 Spa Road, with 111 homes, ground-floor commercial space, and estimated completion in August 2022.",
    observed_change: "A Bermondsey residential and ground-floor commercial scheme was recorded as completed.",
    area: "134 Spa Road",
    latitude: 51.4945,
    longitude: -0.0738,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Dockley Apartments",
    source_url: "https://nla.london/projects/dockley-apartments",
    source_record_id: "nla-dockley-apartments",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Studio Woodroffe Papa, Poggi Architecture, Legendre UK, Max Fordham, Elliott Wood, and project team",
    project_type: "residential development with commercial ground floor",
    geometry_source: "Approximate point geocoded from NLA-stated 134 Spa Road location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. The event records built status and estimated completion month; sales, lettings, and commercial occupancy are outside this record."
  },
  {
    city_id: "london",
    event_id: "lon_arch_national_gallery_sainsbury_wing_completion_2024",
    date: "2024-01-01",
    bucket: "planning/development/architecture/cultural heritage retrofit",
    title: "National Gallery Sainsbury Wing works were listed as built",
    summary: "NLA records the National Gallery project as a built Westminster cultural project, reimagining the Sainsbury Wing entrance, public forecourt, and visitor facilities while conserving the Grade I listed postmodern building, with completion in 2024.",
    observed_change: "A central London gallery entrance, forecourt, and visitor-facility retrofit was recorded as completed.",
    area: "National Gallery, Trafalgar Square",
    latitude: 51.5089,
    longitude: -0.1283,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: The National Gallery",
    source_url: "https://nla.london/projects/the-national-gallery",
    source_record_id: "nla-national-gallery-sainsbury-wing",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Selldorf Architects, Purcell, The National Gallery, and project team",
    project_type: "cultural heritage retrofit and public realm",
    geometry_source: "Approximate point geocoded from NLA-stated Trafalgar Square location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Year-only completion is represented as the first day of the stated year; visitor numbers and operational outcomes require separate source records."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_east_midtown_rezoning_adopted_2017",
    date: "2017-08-09",
    bucket: "planning/development/zoning/office district",
    title: "East Midtown zoning text amendment was adopted",
    summary: "The NYC Zoning Resolution records the East Midtown Subdistrict regulations as amended on August 9, 2017, following the Greater East Midtown rezoning process for the office district around Grand Central Terminal.",
    observed_change: "A documented zoning text change was recorded for the East Midtown office district and its public-realm and development-rights framework.",
    area: "East Midtown, Manhattan",
    latitude: 40.754,
    longitude: -73.973,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Zoning Resolution: East Midtown Subdistrict",
    source_url: "https://zr.planning.nyc.gov/entityprint/pdf/node/19857",
    source_record_id: "nyc-zr-east-midtown-subdistrict-2017-08-09",
    source_retrieved_at: retrievedAt,
    source_date_field: "Zoning Resolution last amended date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC Department of City Planning, City Planning Commission, City Council, and public review participants",
    project_type: "zoning text amendment",
    geometry_source: "Approximate point placed at the East Midtown / Grand Central district rather than a parcel boundary.",
    geometry_precision: "district",
    limitations: "The event records adoption of zoning rules. It does not document any single building permit, public-realm project, development-rights transfer, or construction outcome."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_gowanus_neighborhood_plan_adopted_2021",
    date: "2021-11-23",
    bucket: "planning/development/zoning/mixed use district",
    title: "Gowanus Neighborhood Plan zoning text was adopted",
    summary: "The NYC Zoning Resolution records the Gowanus Neighborhood Plan text amendment, N 210178 ZRK, with an adopted date of November 23, 2021, creating the Special Gowanus Mixed Use District provisions.",
    observed_change: "A documented zoning text change was recorded for the Gowanus mixed-use district framework.",
    area: "Gowanus, Brooklyn",
    latitude: 40.676,
    longitude: -73.992,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Zoning Resolution recently adopted page: Gowanus Neighborhood Plan",
    source_url: "https://zr.planning.nyc.gov/recently-adopted/gowanus-neighborhood-plan-n-210178-zrk",
    source_record_id: "nyc-zr-gowanus-neighborhood-plan-n-210178-zrk",
    source_retrieved_at: retrievedAt,
    source_date_field: "Zoning Resolution adopted date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC Department of City Planning, City Planning Commission, City Council, and public review participants",
    project_type: "zoning text amendment",
    geometry_source: "Approximate point placed within Gowanus rather than a mapped zoning boundary.",
    geometry_precision: "district",
    limitations: "The event records adoption of zoning text. It does not confirm later individual developments, canal remediation progress, infrastructure delivery, or housing completions."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_soho_noho_neighborhood_plan_adopted_2021",
    date: "2021-12-15",
    bucket: "planning/development/zoning/mixed use district",
    title: "SoHo-NoHo Neighborhood Plan zoning text was adopted",
    summary: "The NYC Zoning Resolution records the SoHo-NoHo Neighborhood Plan text amendment, N 210423 ZRM, with an adopted date of December 15, 2021, adding the Special SoHo-NoHo Mixed Use District framework.",
    observed_change: "A documented zoning text change was recorded for the SoHo and NoHo mixed-use district framework.",
    area: "SoHo and NoHo, Manhattan",
    latitude: 40.724,
    longitude: -73.999,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Zoning Resolution recently adopted page: SoHo-NoHo Neighborhood Plan",
    source_url: "https://zr.planning.nyc.gov/recently-adopted/soho-noho-neighborhood-plan-n-210423-zrm",
    source_record_id: "nyc-zr-soho-noho-neighborhood-plan-n-210423-zrm",
    source_retrieved_at: retrievedAt,
    source_date_field: "Zoning Resolution adopted date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC Department of City Planning, City Planning Commission, City Council, and public review participants",
    project_type: "zoning text amendment",
    geometry_source: "Approximate point placed within the SoHo/NoHo plan area rather than a mapped zoning boundary.",
    geometry_precision: "district",
    limitations: "The event records adoption of zoning text. It does not confirm later permits, loft-legalization outcomes, displacement effects, or construction completions."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_city_of_yes_housing_opportunity_adopted_2024",
    date: "2024-12-05",
    bucket: "planning/development/zoning/citywide housing",
    title: "City of Yes for Housing Opportunity zoning text was adopted",
    summary: "The NYC Zoning Resolution records City of Yes for Housing Opportunity, N 240290 ZRY, with an adopted date of December 5, 2024, as a citywide zoning text amendment.",
    observed_change: "A documented citywide zoning text change was recorded for New York City's housing and development-rule framework.",
    area: "New York City",
    latitude: 40.7128,
    longitude: -74.006,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Zoning Resolution recently adopted page: City of Yes for Housing Opportunity",
    source_url: "https://zr.planning.nyc.gov/recently-adopted/city-yes-housing-opportunity-n-240290-zry",
    source_record_id: "nyc-zr-city-of-yes-housing-opportunity-n-240290-zry",
    source_retrieved_at: retrievedAt,
    source_date_field: "Zoning Resolution adopted date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC Department of City Planning, City Planning Commission, City Council, and public review participants",
    project_type: "citywide zoning text amendment",
    geometry_source: "Citywide policy record represented by an approximate New York City civic-center point.",
    geometry_precision: "citywide",
    limitations: "The event records adoption of citywide zoning text. It is not a built-project record and does not quantify subsequent permits, housing starts, or completions."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_midtown_south_mixed_use_plan_adopted_2025",
    date: "2025-08-14",
    bucket: "planning/development/zoning/mixed use district",
    title: "Midtown South Mixed-Use Plan zoning text was adopted",
    summary: "The NYC Zoning Resolution records the Midtown South Mixed-Use Plan, N 250186 ZRM, with an adopted date of August 14, 2025, amending zoning text for Manhattan Community Districts 4 and 5.",
    observed_change: "A documented zoning text change was recorded for the Midtown South mixed-use planning framework.",
    area: "Midtown South, Manhattan",
    latitude: 40.7502,
    longitude: -73.989,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Zoning Resolution recently adopted page: Midtown South Mixed-Use Plan",
    source_url: "https://zr.planning.nyc.gov/recently-adopted/midtown-south-mixed-use-plan-n-250186-zrm",
    source_record_id: "nyc-zr-midtown-south-mixed-use-plan-n-250186-zrm",
    source_retrieved_at: retrievedAt,
    source_date_field: "Zoning Resolution adopted date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC Department of City Planning, City Planning Commission, City Council, and public review participants",
    project_type: "zoning text amendment",
    geometry_source: "Approximate point placed within Midtown South rather than a mapped zoning boundary.",
    geometry_precision: "district",
    limitations: "The event records adoption of zoning text. It does not confirm later conversions, permits, public-realm changes, or building completions."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_ldp_plan_strategy_adopted_2023",
    date: "2023-05-02",
    bucket: "planning/development/planning policy/local development plan",
    title: "Belfast Local Development Plan Strategy was adopted",
    summary: "Belfast City Council records that the Belfast Local Development Plan Plan Strategy was adopted on 2 May 2023 and took effect from that date.",
    observed_change: "A documented citywide planning-policy framework for Belfast development decisions became operative.",
    area: "Belfast City Council area",
    latitude: 54.5964,
    longitude: -5.93,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Local Development Plan page",
    source_url: "https://www.belfastcity.gov.uk/ldp",
    source_record_id: "bcc-ldp-plan-strategy-adoption-2023-05-02",
    source_retrieved_at: retrievedAt,
    source_date_field: "Council-stated Plan Strategy adoption date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Belfast City Council Planning Service, Department for Infrastructure, Planning Appeals Commission, and public consultation participants",
    project_type: "local development plan adoption",
    geometry_source: "Citywide planning-policy record represented by an approximate Belfast civic-centre point.",
    geometry_precision: "citywide",
    limitations: "The event records adoption of planning policy, not a construction milestone. Site-specific zoning, applications, permissions, and completions require separate source records."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_school_of_music_redevelopment_funding_confirmed_2025",
    date: "2025-05-19",
    bucket: "planning/development/heritage/community regeneration",
    title: "Former School of Music redevelopment funding package was noted",
    summary: "Belfast South Area Working Group minutes recorded the former School of Music redevelopment as a Stage 3 committed Neighbourhood Regeneration Fund project, with NRF and Urban Villages capital funding noted and a business case in development.",
    observed_change: "A documented regeneration funding and delivery-status milestone was recorded for reuse of the former School of Music building.",
    area: "Former School of Music, Apsley Street",
    latitude: 54.5862,
    longitude: -5.9377,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council South Belfast Area Working Group minutes: 19 May 2025",
    source_url: "https://minutes.belfastcity.gov.uk/documents/s121679/Minutes%20of%20the%20meeting%20ot%20the%20SBAWG%2019.05.25.pdf",
    source_record_id: "bcc-sbawg-2025-05-19-former-school-of-music",
    source_retrieved_at: retrievedAt,
    source_date_field: "Area Working Group meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Fitzroy Presbyterian Church, Belfast City Council, Urban Villages, and project team; design team not named in source extract",
    project_type: "heritage building redevelopment funding milestone",
    geometry_source: "Approximate point geocoded from former School of Music / Apsley Street location named in council records.",
    geometry_precision: "site",
    limitations: "The event records funding and business-case status. It does not confirm planning permission, construction start, restoration completion, or later cultural programming."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_lagan_water_access_hub_planning_submitted_2025",
    date: "2025-05-19",
    bucket: "planning/development/waterfront recreation",
    title: "Lagan Water Access Activity Hub planning submission was noted",
    summary: "Belfast South Area Working Group minutes recorded the Lagan Water Access Activity Hub as a Stage 3 committed project, noting that boathouse design had been prepared, ground surveys undertaken, and a planning application submitted in April 2025.",
    observed_change: "A documented planning-submission and design-status milestone was recorded for a River Lagan water access hub.",
    area: "River Lagan, Lower Ormeau",
    latitude: 54.5868,
    longitude: -5.9169,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council South Belfast Area Working Group minutes: 19 May 2025",
    source_url: "https://minutes.belfastcity.gov.uk/documents/s121679/Minutes%20of%20the%20meeting%20ot%20the%20SBAWG%2019.05.25.pdf",
    source_record_id: "bcc-sbawg-2025-05-19-lagan-water-access-activity-hub",
    source_retrieved_at: retrievedAt,
    source_date_field: "Area Working Group meeting date noting April 2025 planning submission",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Lower Ormeau Residents' Action Group, Belfast City Council, and project team; design team not named in source extract",
    project_type: "waterfront recreation hub planning submission",
    geometry_source: "Approximate point placed on the Lower Ormeau / River Lagan project area named in council records.",
    geometry_precision: "area",
    limitations: "The event records design and planning-submission status. It does not confirm planning approval, construction start, opening, river access operations, or environmental consents."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_market_heritage_hub_purchase_completed_2025",
    date: "2025-11-24",
    bucket: "planning/development/heritage/community regeneration",
    title: "Market Heritage Hub building purchase was recorded as completed",
    summary: "Belfast South Area Working Group papers recorded the Market Heritage Hub as a Stage 3 committed project and noted that building purchase had been completed with Neighbourhood Regeneration Fund and Community Ownership Fund support.",
    observed_change: "A documented acquisition milestone was recorded for the Market Heritage Hub restoration and heritage-facility project.",
    area: "Market area, Sussex Place",
    latitude: 54.5907,
    longitude: -5.9214,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council South Belfast Area Working Group paper: 24 November 2025",
    source_url: "https://minutes.belfastcity.gov.uk/documents/s125219/SBAWG%2024.11.25.pdf",
    source_record_id: "bcc-sbawg-2025-11-24-market-heritage-hub",
    source_retrieved_at: retrievedAt,
    source_date_field: "Area Working Group paper date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Market Development Association, Belfast City Council, Community Ownership Fund, and project team; design team not named in source extract",
    project_type: "heritage building acquisition and regeneration milestone",
    geometry_source: "Approximate point geocoded from Market / Sussex Place project description in council records.",
    geometry_precision: "area",
    limitations: "The event records building purchase and funding status. It does not confirm restoration design approval, construction start, opening, or Heritage Fund award outcome."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_belfast_stories_design_development_agreed_2025",
    date: "2025-11-21",
    bucket: "planning/development/architecture/cultural visitor destination",
    title: "Belfast Stories enhanced design development was agreed",
    summary: "Belfast Strategic Policy and Resources Committee agreed to proceed with design development including enhanced studio and event-space provision within the Belfast Stories planning application, and to complete an Outline Business Case addendum.",
    observed_change: "A documented governance milestone was recorded for design development of the Belfast Stories cultural and visitor-destination proposal.",
    area: "Royal Avenue, North Street, Union Street and Kent Street",
    latitude: 54.6022,
    longitude: -5.9298,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Strategic Policy and Resources Committee minutes: 21 November 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=163&MeetingId=12017",
    source_record_id: "bcc-spr-2025-11-21-belfast-stories-design-development",
    source_retrieved_at: retrievedAt,
    source_date_field: "Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Belfast City Council, Snohetta, TODD Architects, and project team",
    project_type: "cultural building design-development governance milestone",
    geometry_source: "Approximate point geocoded from the council-stated Belfast Stories site bounded by Royal Avenue, North Street, Union Street, and Kent Street.",
    geometry_precision: "site",
    limitations: "The event records a committee decision to continue design development and business-case work. It does not confirm planning approval, procurement, construction start, opening, or final capital scope."
  }
];

const existingIds = new Set(doc.events.map((event) => event.event_id));
const duplicateIds = records.filter((event) => existingIds.has(event.event_id)).map((event) => event.event_id);
if (duplicateIds.length > 0) {
  throw new Error(`Duplicate event_id values: ${duplicateIds.join(", ")}`);
}

doc.events.push(...records);
doc.sources = doc.sources.map((source) => {
  if (
    source.source_id === "london-architecture-public-pages" ||
    source.source_id === "nyc-architecture-public-pages" ||
    source.source_id === "belfast-architecture-public-pages"
  ) {
    return {
      ...source,
      retrieved_at: retrievedAt
    };
  }
  return source;
});

fs.writeFileSync(path, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`Appended ${records.length} records to ${path}`);
