const fs = require("fs");

const path = "data/manual_drops/architecture_milestones/architecture_milestones_2008_2026.json";
const doc = JSON.parse(fs.readFileSync(path, "utf8"));

const retrievedAt = "2026-05-17";

const records = [
  {
    city_id: "london",
    event_id: "lon_arch_here_east_public_realm_completion_2016",
    date: "2016-01-01",
    bucket: "planning/development/public realm/innovation district",
    title: "Here East public realm was listed as built",
    summary: "NLA records Here East Public Realm as a built Hackney project at Queen Elizabeth Olympic Park, with 62,000 square metres of public realm and completion in 2016.",
    observed_change: "A large public-realm package with yard spaces, pop-up areas, planting, and seating was recorded as completed around the Here East innovation campus.",
    area: "Here East, Queen Elizabeth Olympic Park",
    latitude: 51.546,
    longitude: -0.0222,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Here East Public Realm",
    source_url: "https://nla.london/projects/here-east-public-realm",
    source_record_id: "nla-here-east-public-realm",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "LDA Design, Hawkins Brown, Buro Happold, Gardiner and Theobald, Here East, Delancey, and project team",
    project_type: "public realm for innovation campus",
    geometry_source: "Approximate point geocoded from NLA-stated 1 East Bay Lane / Here East location.",
    geometry_precision: "campus",
    limitations: "Source is a curated project page. Year-only completion is represented as the first day of the stated year; individual landscape elements and later campus operations require separate evidence."
  },
  {
    city_id: "london",
    event_id: "lon_arch_deptford_market_yard_completion_2016",
    date: "2016-01-01",
    bucket: "planning/development/public realm/market and commercial reuse",
    title: "Deptford Market Yard was listed as built",
    summary: "NLA records Deptford Market Yard as a built Lewisham project with commercial spaces in railway arches, a refurbished carriage ramp, landscaped public space, and completion in 2016.",
    observed_change: "Railway arches and adjacent public spaces by Deptford station were recorded as converted into commercial units and a new market court.",
    area: "Deptford Market Yard, Deptford High Street",
    latitude: 51.4776,
    longitude: -0.026,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Deptford Market Yard",
    source_url: "https://nla.london/projects/deptford-market-yard",
    source_record_id: "nla-deptford-market-yard",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Pollard Thomas Edwards, Farrer Huxley, U+I, London Borough of Lewisham, and project team",
    project_type: "railway-arch commercial reuse and public realm",
    geometry_source: "Approximate point geocoded from NLA-stated Deptford High Street location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Year-only completion is represented as the first day of the stated year; tenancy changes and later market operations are not inferred."
  },
  {
    city_id: "london",
    event_id: "lon_arch_cargo_crossrail_place_refurbishment_completion_2022",
    date: "2022-02-01",
    bucket: "planning/development/architecture/office refurbishment",
    title: "Cargo Crossrail Place refurbishment was listed as built",
    summary: "NLA records Cargo Crossrail Place as a built Tower Hamlets office transformation at 25 North Colonnade, with completion in February 2022.",
    observed_change: "A single-tenant Canary Wharf office building was recorded as refurbished and repositioned through a documented design project.",
    area: "25 North Colonnade, Canary Wharf",
    latitude: 51.5054,
    longitude: -0.0197,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Cargo Crossrail Place",
    source_url: "https://nla.london/projects/cargo-crossrail-place",
    source_record_id: "nla-cargo-crossrail-place",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Gensler, Revantage, Blackstone, Gardiner and Theobald, Alinea, ISG, Arup, and project team",
    project_type: "office refurbishment",
    geometry_source: "Approximate point geocoded from NLA-stated 25 North Colonnade location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. The event records built status and completion month; leasing, occupancy, and operational performance require separate source records."
  },
  {
    city_id: "london",
    event_id: "lon_arch_starling_house_completion_2019",
    date: "2019-06-01",
    bucket: "planning/development/architecture/residential",
    title: "Starling House was listed as built",
    summary: "NLA records Starling House as a built Barnet residential project at 53 Tyrrel Way, with estimated completion in June 2019.",
    observed_change: "A residential building within the wider Colindale regeneration area was recorded as completed.",
    area: "Starling House, 53 Tyrrel Way",
    latitude: 51.5959,
    longitude: -0.2515,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Starling House",
    source_url: "https://nla.london/projects/starling-house",
    source_record_id: "nla-starling-house",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Makower Architects listed the project, with masterplan by Allies and Morrison, landscape by Exterior Architecture, Barratt London, Metropolitan Thames Valley Housing, London Borough of Barnet, and project team",
    project_type: "residential building",
    geometry_source: "Approximate point geocoded from NLA-stated 53 Tyrrel Way location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page with an estimated completion month. Tenure mix, occupation, and later estate management require separate source records."
  },
  {
    city_id: "london",
    event_id: "lon_arch_field_house_completion_2020",
    date: "2020-02-01",
    bucket: "planning/development/architecture/residential retrofit",
    title: "Field House was listed as built",
    summary: "NLA records Field House as a built Hackney residential project at London Fields East Side, with completion in February 2020.",
    observed_change: "A London Fields residential building was recorded as completed after a project that introduced a triple-height stairwell, bridge, and new internal light connections.",
    area: "34 London Fields East Side",
    latitude: 51.5431,
    longitude: -0.0593,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Field House",
    source_url: "https://nla.london/projects/field-house",
    source_record_id: "nla-field-house",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Bradley Van Der Straeten Architects, Optimal Build, Constant Structural Design, and project team",
    project_type: "residential refurbishment and extension",
    geometry_source: "Approximate point geocoded from NLA-stated 34 London Fields East Side location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. The event records project completion and does not infer wider neighbourhood impact or later occupation changes."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_broadway_library_astoria_reopening_2024",
    date: "2024-08-12",
    bucket: "planning/development/architecture/library renovation",
    title: "Broadway Library in Astoria reopened after expansion and renovation",
    summary: "NYC DDC and Queens Public Library marked the reopening of Broadway Library after a USD 4.6 million project that transformed the cellar into public-use space with a lobby, computer center, classroom, meeting room, restrooms, HVAC, and finishes.",
    observed_change: "An Astoria library branch was recorded as reopened after lower-level expansion, interior renovation, building-system work, and accessibility upgrades.",
    area: "Broadway Library, Astoria",
    latitude: 40.7593,
    longitude: -73.918,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Broadway Library reopening",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-081224-BroadwayLibrary.page",
    source_record_id: "nyc-ddc-pr-081224-broadway-library",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "Queens Public Library, NYC DDC, and project team; architect not named in source extract",
    project_type: "library expansion and renovation",
    geometry_source: "Approximate point geocoded from DDC-stated Broadway Library / Astoria location.",
    geometry_precision: "site",
    limitations: "The event records public reopening after construction. The source notes construction concluded in October 2023 and reopening was later delayed by budget issues."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_east_side_coastal_resiliency_first_section_completion_2024",
    date: "2024-10-17",
    bucket: "planning/development/infrastructure/coastal resiliency",
    title: "First East Side Coastal Resiliency section was completed",
    summary: "NYC announced completion of the first section of East Side Coastal Resiliency in Manhattan, covering the area north of East 15th Street to Asser Levy Playground with raised parkland, floodwalls, berms, and flood gates.",
    observed_change: "A coastal resiliency project section with parkland, floodwall, berm, and flood-gate works was recorded as completed on Manhattan's East Side.",
    area: "East 15th Street to Asser Levy Playground",
    latitude: 40.7338,
    longitude: -73.9743,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DEP press release: East Side Coastal Resiliency first section",
    source_url: "https://www.nyc.gov/site/dep/news/772-24/mayor-adams-completes-first-section-east-side-coastal-resiliency-project-taking-steps-to",
    source_record_id: "nyc-dep-772-24-escr-first-section",
    source_retrieved_at: retrievedAt,
    source_date_field: "DEP press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC, NYC DEP, NYC Parks, Mayor's Office of Climate and Environmental Justice, and project team",
    project_type: "coastal resiliency and park infrastructure",
    geometry_source: "Approximate point geocoded from source-stated East 15th Street to Asser Levy Playground project section.",
    geometry_precision: "corridor",
    limitations: "The event records a section completion at corridor precision. Related playground, ballfield, bridge, and later East River Park phases have separate records."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_college_point_infrastructure_completion_2024",
    date: "2024-09-25",
    bucket: "planning/development/infrastructure/street and utilities",
    title: "College Point water-main and sewer project was completed",
    summary: "NYC DEP, DOT, and DDC announced completion of a USD 139 million College Point project covering more than 100 blocks, upgrading over six miles of water mains, over eight miles of sewers, streets, sidewalks, ramps, catch basins, hydrants, and wetland areas.",
    observed_change: "A neighbourhood-scale street, sewer, water-main, sidewalk, ramp, catch-basin, hydrant, and wetland-restoration project was recorded as completed in College Point.",
    area: "College Point, Queens",
    latitude: 40.7876,
    longitude: -73.8465,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: College Point infrastructure project",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-092524-CollegePoint.page",
    source_record_id: "nyc-ddc-pr-092524-college-point",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DOT, NYC DDC, and project team",
    project_type: "street, sewer, water-main, and drainage infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated College Point project area.",
    geometry_precision: "neighbourhood",
    limitations: "The event records neighbourhood-scale completion and does not map the 100-plus blocks, pipe alignments, catch basins, hydrants, sidewalks, ramps, or wetland areas individually."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_maspeth_phase2_sewer_completion_2024",
    date: "2024-10-07",
    bucket: "planning/development/infrastructure/sewer and water",
    title: "Maspeth Phase 2 sewer project was completed",
    summary: "NYC DEP and DDC announced completion of Phase 2 of a central Queens drainage programme in Maspeth, including new large-diameter sewers, water mains, catch basins, curbs, sidewalks, ADA ramps, trees, and a bike lane.",
    observed_change: "A major Maspeth sewer, water-main, street-edge, pedestrian, and bike-lane infrastructure phase was recorded as completed.",
    area: "Maspeth, Queens",
    latitude: 40.724,
    longitude: -73.912,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Maspeth Phase 2 sewer project",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-100724-Maspeth.page",
    source_record_id: "nyc-ddc-pr-100724-maspeth-phase-2",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DDC, NYC DOT, and project team",
    project_type: "sewer, water-main, and street infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated Maspeth / Queens Boulevard project area.",
    geometry_precision: "neighbourhood",
    limitations: "The event records the second phase of a multi-phase drainage programme at neighbourhood precision. It does not map individual shafts, pipe alignments, curb segments, ramps, or tree locations."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_forest_hills_rego_park_water_mains_completion_2024",
    date: "2024-05-01",
    bucket: "planning/development/infrastructure/water mains",
    title: "Forest Hills and Rego Park water-main upgrades were completed",
    summary: "NYC DEP and DDC announced completion of a USD 9 million project that upgraded nearly four miles of older water mains in Forest Hills and Rego Park.",
    observed_change: "A water-distribution infrastructure project replacing older mains with ductile iron pipes was recorded as completed in Forest Hills and Rego Park.",
    area: "Forest Hills and Rego Park, Queens",
    latitude: 40.724,
    longitude: -73.853,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DEP press release: Forest Hills and Rego Park water mains",
    source_url: "https://www.nyc.gov/site/dep/news/301-24/nearly-four-miles-water-mains-upgraded-forest-hills-rego-park",
    source_record_id: "nyc-dep-301-24-forest-hills-rego-park-water-mains",
    source_retrieved_at: retrievedAt,
    source_date_field: "DEP press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DDC, and project team",
    project_type: "water-main infrastructure",
    geometry_source: "Approximate point geocoded from DEP-stated Forest Hills and Rego Park project area.",
    geometry_precision: "neighbourhood",
    limitations: "The event records neighbourhood-scale completion and does not map the individual water-main alignments or street segments."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_dairy_farm_transport_hub_approved_2016",
    date: "2016-06-14",
    bucket: "planning/development/architecture/transport hub",
    title: "Dairy Farm transport hub building was approved",
    summary: "Belfast Planning Committee granted approval for a new transport hub building with bus turning lane and access on lands south and west of Dairy Farm Complex, Stewartstown Road.",
    observed_change: "A documented planning approval was recorded for a transport hub building and bus access works at Dairy Farm.",
    area: "Dairy Farm Complex, Stewartstown Road",
    latitude: 54.5658,
    longitude: -6.0064,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 14 June 2016",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=5844",
    source_record_id: "bcc-planning-2016-06-14-dairy-farm-transport-hub-la04-2016-0430",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "transport hub planning approval",
    geometry_source: "Approximate point geocoded from committee-stated Dairy Farm Complex / Stewartstown Road location.",
    geometry_precision: "site",
    limitations: "The event records committee approval only. Final permission wording, construction, and operation require separate evidence."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_sydenham_porsche_centre_approved_2016",
    date: "2016-06-14",
    bucket: "planning/development/architecture/commercial automotive",
    title: "Sydenham Road Porsche centre was approved",
    summary: "Belfast Planning Committee granted approval for a Porsche motor-vehicle sales and service centre with workshop, parts storage, and office accommodation on lands at Sydenham Road bounded by Cuming Road and Hamilton Road.",
    observed_change: "A documented planning approval was recorded for a commercial automotive building and associated workshop and office accommodation in the harbour area.",
    area: "Sydenham Road / Cuming Road / Hamilton Road",
    latitude: 54.6095,
    longitude: -5.8801,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 14 June 2016",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=5844",
    source_record_id: "bcc-planning-2016-06-14-sydenham-porsche-centre-la04-2016-0089",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "commercial motor centre planning approval",
    geometry_source: "Approximate point geocoded from committee-stated Sydenham Road / Cuming Road / Hamilton Road location.",
    geometry_precision: "site",
    limitations: "The event records committee approval subject to conditions and does not confirm construction start, showroom opening, or later site operation."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_upper_newtownards_road_apartments_approved_2016",
    date: "2016-06-14",
    bucket: "planning/development/architecture/housing",
    title: "24-40 Upper Newtownards Road apartments were approved",
    summary: "Belfast Planning Committee granted approval for change of use from existing furniture store, coffee shop, and hot-food takeaway to nine apartments with elevational changes at 24-40 Upper Newtownards Road.",
    observed_change: "A documented planning approval was recorded for residential conversion and elevational changes in the Holywood Arches area.",
    area: "24-40 Upper Newtownards Road",
    latitude: 54.5991,
    longitude: -5.8898,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 14 June 2016",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=5844",
    source_record_id: "bcc-planning-2016-06-14-upper-newtownards-road-apartments-la04-2015-0233",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "commercial-to-residential conversion approval",
    geometry_source: "Approximate point geocoded from committee-stated 24-40 Upper Newtownards Road location.",
    geometry_precision: "site",
    limitations: "The event records committee approval and does not confirm implementation, unit occupation, or later alterations."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_falls_road_apartments_retail_approved_2016",
    date: "2016-06-14",
    bucket: "planning/development/architecture/housing and retail",
    title: "39-41 Falls Road apartments and retail unit were approved",
    summary: "Belfast Planning Committee granted full planning permission for demolition of an existing building and erection of 11 apartments and one retail unit with landscaping and associated site works at 39/41 Falls Road.",
    observed_change: "A documented planning approval was recorded for a small mixed residential and retail redevelopment on Falls Road.",
    area: "39/41 Falls Road",
    latitude: 54.5981,
    longitude: -5.9367,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 14 June 2016",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=5844",
    source_record_id: "bcc-planning-2016-06-14-falls-road-apartments-retail-la04-2015-1472",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "mixed residential and retail planning approval",
    geometry_source: "Approximate point geocoded from committee-stated 39/41 Falls Road address.",
    geometry_precision: "site",
    limitations: "The event records planning approval only. Demolition, construction, retail fit-out, and occupation require separate source records."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_upper_crumlin_recycling_building_approved_2016",
    date: "2016-06-14",
    bucket: "planning/development/architecture/waste facility",
    title: "1080 Upper Crumlin Road recycling building was approved",
    summary: "Belfast Planning Committee granted approval for retention of an existing recycling facility building and erection of a new recycling facility building with associated retaining wall at 1080 Upper Crumlin Road.",
    observed_change: "A documented planning approval was recorded for recycling-facility building retention and new waste-facility building works.",
    area: "1080 Upper Crumlin Road",
    latitude: 54.6425,
    longitude: -5.9926,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 14 June 2016",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=5844",
    source_record_id: "bcc-planning-2016-06-14-upper-crumlin-recycling-building-z-2009-0688",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "recycling facility building planning approval",
    geometry_source: "Approximate point geocoded from committee-stated 1080 Upper Crumlin Road location.",
    geometry_precision: "site",
    limitations: "The event records approval for retention and new building works. It does not confirm later construction, operation, or environmental-permit status."
  }
];

const existingIds = new Set(doc.events.map((event) => event.event_id));
const duplicateIds = records.filter((event) => existingIds.has(event.event_id)).map((event) => event.event_id);
if (duplicateIds.length > 0) {
  throw new Error(`Duplicate event_id values: ${duplicateIds.join(", ")}`);
}

doc.events.push(...records);
doc.sources = doc.sources.map((source) => {
  if (
    source.source_id === "london-architecture-public-pages" ||
    source.source_id === "nyc-architecture-public-pages" ||
    source.source_id === "belfast-architecture-public-pages"
  ) {
    return {
      ...source,
      retrieved_at: retrievedAt
    };
  }
  return source;
});

fs.writeFileSync(path, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`Appended ${records.length} records to ${path}`);
