const fs = require("fs");

const path = "data/manual_drops/architecture_milestones/architecture_milestones_2008_2026.json";
const doc = JSON.parse(fs.readFileSync(path, "utf8"));

const retrievedAt = "2026-05-17";

const records = [
  {
    city_id: "london",
    event_id: "lon_arch_lj_works_loughborough_farm_completion_2023",
    date: "2023-04-01",
    bucket: "planning/development/architecture/workspace",
    title: "LJ Works and Loughborough Farm were listed as built",
    summary: "NLA records LJ Works and Loughborough Farm as a built neighbourhood workspace and farm project at Loughborough Road / Hopton House, with completion in April 2023.",
    observed_change: "Neighbourhood workspace, maker-space, co-working, meeting, and farm facilities were recorded as completed at Loughborough Road / Hopton House.",
    area: "Loughborough Road / Hopton House, Lambeth",
    latitude: 51.4666,
    longitude: -0.1113,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: LJ Works & Loughborough Farm",
    source_url: "https://www.nla.london/projects/lj-works-loughborough-farm",
    source_record_id: "nla-lj-works-loughborough-farm",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Architecture 00; Public Works",
    project_type: "neighbourhood workspace and urban farm",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source is a curated project page, not a planning register entry. Completion month is used as an approximate effective date."
  },
  {
    city_id: "london",
    event_id: "lon_arch_newsons_yard_completion_2022",
    date: "2022-07-01",
    bucket: "planning/development/architecture/retail-hospitality",
    title: "Newson's Yard was listed as built",
    summary: "NLA records Newson's Yard at 65a Pimlico Road as a built redevelopment of London's oldest timber yard, with completion in July 2022.",
    observed_change: "The former timber-yard site was recorded as reconfigured into retail, hospitality, and residential space with a public route through the site.",
    area: "65a Pimlico Road, Westminster",
    latitude: 51.4906,
    longitude: -0.1572,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Newson's Yard",
    source_url: "https://nla.london/projects/newsons-yard",
    source_record_id: "nla-newsons-yard",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Stiff + Trevillion",
    project_type: "heritage-led retail and residential redevelopment",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source is a curated project page and uses an estimated completion month; detailed consent conditions are outside this record."
  },
  {
    city_id: "london",
    event_id: "lon_arch_lao_dao_walworth_road_completion_2023",
    date: "2023-01-01",
    bucket: "planning/development/architecture/conservation",
    title: "Lao Dao Walworth Road was listed as built",
    summary: "NLA records Lao Dao, Walworth Road as a built restoration of a Grade II listed Art Deco former sausage shop into a restaurant, with completion in 2023.",
    observed_change: "The listed shopfront at 305 Walworth Road was recorded as restored and reused as a restaurant.",
    area: "305 Walworth Road, Southwark",
    latitude: 51.4858,
    longitude: -0.0954,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Lao Dao, Walworth Road",
    source_url: "https://nla.london/projects/lao-dao-walworth-road",
    source_record_id: "nla-lao-dao-walworth-road",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "IDK",
    project_type: "listed shopfront restoration and restaurant fit-out",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source gives completion year rather than an exact day; date is set to the start of the documented year."
  },
  {
    city_id: "london",
    event_id: "lon_arch_paper_garden_completion_2023",
    date: "2023-01-01",
    bucket: "planning/development/architecture/meanwhile",
    title: "The Paper Garden was listed as built",
    summary: "NLA records The Paper Garden at the Mast Leisure Complex as a built reuse of a disused industrial shed, with completion in 2023.",
    observed_change: "A disused industrial shed at Canada Water was recorded as repurposed for community garden and education activity.",
    area: "The Mast Leisure Complex, Canada Water",
    latitude: 51.4984,
    longitude: -0.0475,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: The Paper Garden",
    source_url: "https://www.nla.london/projects/the-paper-garden",
    source_record_id: "nla-the-paper-garden",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Jan Kattein Architects",
    project_type: "meanwhile community garden and shed reuse",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source gives completion year rather than an exact day; date is set to the start of the documented year."
  },
  {
    city_id: "london",
    event_id: "lon_arch_plantworks_completion_2021",
    date: "2021-05-01",
    bucket: "planning/development/architecture/workplace-retrofit",
    title: "Plantworks was listed as built",
    summary: "NLA records Plantworks at 108 Britton Street as a built conversion of a former mirror warehouse into office workspace, with completion in May 2021.",
    observed_change: "A former workshop/warehouse building was recorded as transformed into a modern office workspace with integrated planting.",
    area: "108 Britton Street, Camden",
    latitude: 51.5204,
    longitude: -0.1027,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Plantworks",
    source_url: "https://nla.london/projects/plantworks",
    source_record_id: "nla-plantworks",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Marek Wojciechowski Architects Ltd",
    project_type: "warehouse-to-workplace retrofit",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source is a curated project page, not a full planning history. Completion month is used as an approximate effective date."
  },
  {
    city_id: "london",
    event_id: "lon_arch_symes_mews_completion_2021",
    date: "2021-01-01",
    bucket: "planning/development/architecture/workplace-retrofit",
    title: "Symes Mews was listed as built",
    summary: "NLA records Symes Mews at 35 Camden High Street as a built refurbishment and extension of a former furniture warehouse, with completion in 2021.",
    observed_change: "A former furniture warehouse was recorded as refurbished and extended into creative workspace.",
    area: "35 Camden High Street, Camden",
    latitude: 51.5367,
    longitude: -0.14,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Symes Mews",
    source_url: "https://nla.london/projects/symes-mews",
    source_record_id: "nla-symes-mews",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "pH+ Architects",
    project_type: "creative workspace retrofit",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source gives completion year rather than an exact day; date is set to the start of the documented year."
  },
  {
    city_id: "london",
    event_id: "lon_arch_warbank_crescent_completion_2021",
    date: "2021-08-01",
    bucket: "planning/development/architecture/housing",
    title: "Warbank Crescent was listed as built",
    summary: "NLA records Warbank Crescent in New Addington as a built 36-unit social housing scheme, with estimated completion in August 2021.",
    observed_change: "A 36-unit social housing scheme was recorded as completed at Warbank Crescent.",
    area: "48 Warbank Crescent, New Addington, Croydon",
    latitude: 51.3439,
    longitude: -0.0189,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Warbank Crescent",
    source_url: "https://nla.london/projects/warbank-crescent",
    source_record_id: "nla-warbank-crescent",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Coffey Architects",
    project_type: "social housing",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source is a curated project page and uses an estimated completion month; tenure and unit details should be checked against council records for formal reporting."
  },
  {
    city_id: "london",
    event_id: "lon_arch_driving_for_change_completion_2021",
    date: "2021-11-01",
    bucket: "planning/development/architecture/adaptive-reuse",
    title: "Driving for Change mobile service fit-out was listed as built",
    summary: "NLA records Driving for Change as a built adaptation of two London buses into mobile support facilities, with completion in November 2021.",
    observed_change: "Two London buses were recorded as repurposed into mobile service spaces with healthcare, hygiene, and support facilities.",
    area: "58 Chadwick Road, Southwark",
    latitude: 51.4707,
    longitude: -0.061,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Driving for Change",
    source_url: "https://www.nla.london/projects/driving-for-change",
    source_record_id: "nla-driving-for-change",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "TP Bennett",
    project_type: "mobile adaptive-reuse service fit-out",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "project base / representative point",
    limitations: "Mobile service geography differs from a fixed building; point is a representative source location, not a full operating route."
  },
  {
    city_id: "london",
    event_id: "lon_arch_meta_office_canal_reach_completion_2021",
    date: "2021-01-01",
    bucket: "planning/development/architecture/workplace",
    title: "Meta Office at Canal Reach was listed as built",
    summary: "NLA records Meta Office at 11-21 Canal Reach as a built office development in King's Cross, with completion in 2021.",
    observed_change: "A large office building at Canal Reach was recorded as completed with rooftop garden and workplace space.",
    area: "5 Canal Reach, King's Cross",
    latitude: 51.5379,
    longitude: -0.1253,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Meta Office (11-21 Canal Reach)",
    source_url: "https://nla.london/projects/meta-office-11-21-canal-reach",
    source_record_id: "nla-meta-office-11-21-canal-reach",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Bennetts Associates; TP Bennett; Gehry Partners / Meta",
    project_type: "office development",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source gives completion year rather than an exact day; date is set to the start of the documented year."
  },
  {
    city_id: "london",
    event_id: "lon_arch_tower_court_completion_2024",
    date: "2024-01-01",
    bucket: "planning/development/architecture/housing",
    title: "Tower Court was listed as built",
    summary: "NLA records Tower Court in Hackney as a built 132-home mixed-tenure housing scheme, with completion in 2024.",
    observed_change: "A 132-home mixed-tenure housing scheme was recorded as completed around Clapton Common.",
    area: "Clapton Common, Hackney",
    latitude: 51.5703,
    longitude: -0.0647,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Tower Court",
    source_url: "https://nla.london/projects/tower-court",
    source_record_id: "nla-tower-court",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Adam Khan Architects; Child Graddon Lewis; muf architecture/art; Tom Stebbing; J & L Gibbons",
    project_type: "mixed-tenure housing",
    geometry_source: "Approximate point geocoded from NLA location field",
    geometry_precision: "site",
    limitations: "Source gives completion year rather than an exact day; date is set to the start of the documented year."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_whitestone_storm_sewers_completion_2024",
    date: "2024-05-28",
    bucket: "planning/development/architecture/infrastructure",
    title: "Whitestone storm-sewer projects were announced complete",
    summary: "NYC DDC and partner agencies announced completion of two Whitestone infrastructure projects totaling $128 million and adding nearly six miles of storm sewers.",
    observed_change: "New storm sewers, converted sanitary sewers, water-main replacements, sidewalks, curbs, and pedestrian ramps were documented across more than 120 blocks in Whitestone and North Flushing.",
    area: "Whitestone and North Flushing, Queens",
    latitude: 40.787,
    longitude: -73.814,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: Whitestone storm sewers",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-052824-Whitestone.page",
    source_record_id: "nyc-ddc-pr-052824-whitestone",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC / DEP / DOT; design team not specified by source",
    project_type: "stormwater, street, and water infrastructure",
    geometry_source: "Approximate neighborhood centroid from source project area",
    geometry_precision: "neighborhood",
    limitations: "Release date is used as the documented public completion milestone; source states construction concluded in 2023."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_tide_gate_bridge_reconstruction_groundbreaking_2024",
    date: "2024-05-28",
    bucket: "planning/development/architecture/bridge",
    title: "Tide Gate Bridge reconstruction broke ground",
    summary: "NYC Parks and DDC announced the start of a $41 million reconstruction of Tide Gate Bridge, also known as Porpoise Bridge, in Flushing Meadows Corona Park.",
    observed_change: "Construction start was documented for replacement of the bridge deck, flood-control structures, sidewalks, utilities, and shoreline wetland work.",
    area: "Tide Gate Bridge, Flushing Meadows Corona Park",
    latitude: 40.748,
    longitude: -73.839,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: Tide Gate Bridge reconstruction",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-052824-TideGateBridge.page",
    source_record_id: "nyc-ddc-pr-052824-tide-gate-bridge",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC / NYC Parks; design team not specified by source",
    project_type: "bridge and flood-control reconstruction",
    geometry_source: "Approximate point geocoded from source location",
    geometry_precision: "site",
    limitations: "This is a construction-start milestone; completion was projected for a later date and is not treated as observed completion."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_westerleigh_infrastructure_completion_2024",
    date: "2024-02-27",
    bucket: "planning/development/architecture/infrastructure",
    title: "Westerleigh drainage and street upgrades were announced complete",
    summary: "NYC DDC, DEP, and DOT announced completion of a $4.7 million Westerleigh project adding storm sewers and upgrading water mains, sanitary sewers, roads, and sidewalks.",
    observed_change: "Storm-sewer, water-main, sanitary-sewer, roadway, sidewalk, curb, and pedestrian-safety upgrades were documented in Westerleigh.",
    area: "Forest Avenue and North Avenue area, Westerleigh, Staten Island",
    latitude: 40.618,
    longitude: -74.136,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: Westerleigh infrastructure completion",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-022724-Westerleigh.page",
    source_record_id: "nyc-ddc-pr-022724-westerleigh",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC / DEP / DOT; design team not specified by source",
    project_type: "drainage, street, and utility infrastructure",
    geometry_source: "Approximate point geocoded from source project area",
    geometry_precision: "project area",
    limitations: "Release date is used as the documented completion milestone; exact work-front dates vary by block."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_southern_brooklyn_fresh_creek_sewers_completion_2022",
    date: "2022-04-22",
    bucket: "planning/development/architecture/infrastructure",
    title: "Southern Brooklyn Fresh Creek sewer program was announced complete",
    summary: "NYC DDC and DEP announced completion of a $148 million three-phase program in Canarsie and East New York, including 6.5 miles of new sewers and restored wetland areas.",
    observed_change: "Storm sewers, water mains, sanitary sewer work, reconstructed roadways, sidewalks, curbs, and Fresh Creek Basin wetland restoration were documented.",
    area: "Canarsie and East New York, Brooklyn",
    latitude: 40.64,
    longitude: -73.897,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: Southern Brooklyn sewers and Fresh Creek",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2022/pr-042222-sewers.page",
    source_record_id: "nyc-ddc-pr-042222-sewers",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC / DEP; design team not specified by source",
    project_type: "stormwater, utility, street, and wetland infrastructure",
    geometry_source: "Approximate neighborhood centroid from source project area",
    geometry_precision: "neighborhood",
    limitations: "Record summarizes a multi-phase area program; use source details for exact block-level and wetland-zone boundaries."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_south_jamaica_st_albans_infrastructure_completion_2022",
    date: "2022-07-08",
    bucket: "planning/development/architecture/infrastructure",
    title: "South Jamaica and St. Albans sewers and water mains were announced complete",
    summary: "NYC DDC and DEP announced completion of a $24 million project adding nearly two miles of new sewers and water mains in South Jamaica and St. Albans.",
    observed_change: "Storm sewers, sanitary sewers, water mains, repaved roadway, sidewalks, curbs, pedestrian ramps, and trees were documented across nine blocks.",
    area: "South Jamaica and St. Albans, Queens",
    latitude: 40.696,
    longitude: -73.777,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: South Jamaica and St. Albans infrastructure",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2022/pr-070822-SouthJamaica.page",
    source_record_id: "nyc-ddc-pr-070822-south-jamaica",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC in-house team",
    project_type: "sewer, water-main, and street infrastructure",
    geometry_source: "Approximate neighborhood centroid from source project area",
    geometry_precision: "neighborhood",
    limitations: "Record summarizes a multi-block project; exact geometry should be traced to source maps or capital project files."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_new_dorp_beach_street_drainage_completion_2025",
    date: "2025-05-20",
    bucket: "planning/development/architecture/infrastructure",
    title: "New Dorp Beach drainage and street project was announced complete",
    summary: "NYC DDC, DEP, and DOT announced completion of an $84 million New Dorp Beach project that installed storm sewers and rebuilt streets and sidewalks.",
    observed_change: "Storm sewers, catch basins, water mains, sanitary sewers, sidewalks, curbs, pedestrian ramps, street elevation changes, and new asphalt were documented.",
    area: "Roma-Hett project area, New Dorp Beach, Staten Island",
    latitude: 40.565,
    longitude: -74.105,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: New Dorp Beach drainage project",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2025/pr-052025-RomaHett.page",
    source_record_id: "nyc-ddc-pr-052025-roma-hett",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DDC / DEP / DOT; design team not specified by source",
    project_type: "coastal drainage and street reconstruction",
    geometry_source: "Approximate point geocoded from source project area",
    geometry_precision: "project area",
    limitations: "Release describes an area project; exact street extents and property adjustments should be verified against project maps."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_east_flatbush_canarsie_green_infrastructure_completion_2025",
    date: "2025-04-22",
    bucket: "planning/development/architecture/green-infrastructure",
    title: "East Flatbush and Canarsie green infrastructure was announced complete",
    summary: "The Mayor's Office announced completion of a $42.3 million flood-prevention project in East Flatbush and Canarsie, including rain gardens and infiltration basins.",
    observed_change: "Rain gardens, infiltration basins, and new street trees were documented across East Flatbush and Canarsie.",
    area: "East Flatbush and Canarsie, Brooklyn",
    latitude: 40.651,
    longitude: -73.923,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Mayor's Office press release: East Flatbush and Canarsie green infrastructure",
    source_url: "https://www.nyc.gov/mayors-office/news/2025/04/mayor-adams-celebrates-earth-day-announcing-completion-42-million-flood-prevention",
    source_record_id: "nyc-mayor-pr-2025-04-east-flatbush-canarsie-green-infrastructure",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP / DDC; design team not specified by source",
    project_type: "green stormwater infrastructure",
    geometry_source: "Approximate neighborhood centroid from source project area",
    geometry_precision: "neighborhood",
    limitations: "Record summarizes neighborhood-scale assets; it does not enumerate every rain garden, basin, or tree location."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_castle_hill_library_renovation_groundbreaking_2025",
    date: "2025-12-08",
    bucket: "planning/development/architecture/library",
    title: "Castle Hill Library renovation broke ground",
    summary: "NYC DDC and NYPL announced groundbreaking for a $17 million renovation of Castle Hill Library at 947 Castle Hill Avenue.",
    observed_change: "Construction start was documented for a library renovation with a redesigned facade, new reading rooms, skylights, accessibility upgrades, green roof, and systems work.",
    area: "947 Castle Hill Avenue, Bronx",
    latitude: 40.828,
    longitude: -73.85,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: Castle Hill Library renovation",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2025/pr-120825-CastleHillLibrary.page",
    source_record_id: "nyc-ddc-pr-120825-castle-hill-library",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "Abruzzo Bodziak Architects",
    project_type: "public library renovation",
    geometry_source: "Approximate point geocoded from source address",
    geometry_precision: "site",
    limitations: "This is a construction-start milestone; completion was projected for a later date and is not treated as observed completion."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_baisley_park_library_renovation_groundbreaking_2025",
    date: "2025-09-29",
    bucket: "planning/development/architecture/library",
    title: "Baisley Park Library renovation and expansion broke ground",
    summary: "NYC DDC and Queens Public Library announced groundbreaking for a $17.6 million renovation and expansion of Baisley Park Library at 117-11 Sutphin Boulevard.",
    observed_change: "Construction start was documented for a library renovation and expansion with new interior layout, accessibility upgrades, green roof, solar panels, and public art.",
    area: "117-11 Sutphin Boulevard, Jamaica",
    latitude: 40.68,
    longitude: -73.792,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC DDC press release: Baisley Park Library renovation and expansion",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2025/pr-092925-BaisleyParkLibrary.page",
    source_record_id: "nyc-ddc-pr-092925-baisley-park-library",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "LevenBetts",
    project_type: "public library renovation and expansion",
    geometry_source: "Approximate point geocoded from source address",
    geometry_precision: "site",
    limitations: "This is a construction-start milestone; completion was projected for a later date and is not treated as observed completion."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_red_hook_coastal_resiliency_groundbreaking_2025",
    date: "2025-09-16",
    bucket: "planning/development/architecture/coastal-resiliency",
    title: "Red Hook Coastal Resiliency broke ground",
    summary: "The NYC Mayor's Office announced groundbreaking for Red Hook Coastal Resiliency, a $218 million coastal-defense project with floodwalls, floodgates, street redesigns, and public-space upgrades.",
    observed_change: "Construction start was documented for a two-mile integrated coastal-defense system, including floodwalls, floodgates, street redesigns, Todd Triangle public-space work, and Brooklyn Waterfront Greenway extension.",
    area: "Atlantic Basin, Beard Street, and Red Hook waterfront",
    latitude: 40.677,
    longitude: -74.012,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Mayor's Office press release: Red Hook Coastal Resiliency groundbreaking",
    source_url: "https://www.nyc.gov/mayors-office/news/2025/09/mayor-adams-breaks-ground-on--218-million-public-safety-project-",
    source_record_id: "nyc-mayor-pr-2025-09-red-hook-coastal-resiliency",
    source_retrieved_at: retrievedAt,
    source_date_field: "press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP / DDC / partner agencies; design team not specified by source",
    project_type: "coastal resiliency and streetscape infrastructure",
    geometry_source: "Approximate waterfront corridor midpoint from source project area",
    geometry_precision: "corridor midpoint",
    limitations: "This is a construction-start milestone; the point is a representative corridor midpoint and does not describe the full two-mile alignment."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_corporation_street_pbmsa_approved_2025",
    date: "2025-06-17",
    bucket: "planning/development/architecture/student-housing",
    title: "39 Corporation Street PBMSA was granted planning permission",
    summary: "Belfast Planning Committee granted planning permission for LA04/2024/2044/F, an 895-room purpose-built managed student accommodation scheme at 39 Corporation Street.",
    observed_change: "Committee approval was recorded for 9-20 storey PBMSA blocks with communal facilities, landscaped courtyard, roof terraces, and ancillary accommodation.",
    area: "39 Corporation Street",
    latitude: 54.6031,
    longitude: -5.9249,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 17 June 2025",
    source_url: "https://minutes.belfastcity.gov.uk/mgAi.aspx?ID=83840",
    source_record_id: "LA04/2024/2044/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "LIKE Architects",
    project_type: "purpose-built managed student accommodation",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Planning permission is an approval milestone, not evidence that construction started or completed."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_albertbridge_short_term_let_units_approved_2026",
    date: "2026-02-17",
    bucket: "planning/development/architecture/visitor-accommodation",
    title: "341-345 Albertbridge Road short-term-let building was approved",
    summary: "Belfast Planning Committee granted planning permission for LA04/2025/0605/F, a four-storey building with 29 short-term-let accommodation units at 341-345 Albertbridge Road.",
    observed_change: "Committee approval was recorded for a four-storey short-term-let building with roof-mounted solar panels.",
    area: "341-345 Albertbridge Road",
    latitude: 54.5923,
    longitude: -5.8949,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 17 February 2026",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?MId=12348",
    source_record_id: "LA04/2025/0605/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "short-term-let accommodation",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Planning permission is an approval milestone, not evidence that construction started or completed."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_belfast_met_whiterock_social_childrens_centre_approved_2026",
    date: "2026-02-17",
    bucket: "planning/development/architecture/housing-community",
    title: "Former Belfast Met Whiterock social housing and children's centre amendment was approved",
    summary: "Belfast Planning Committee granted planning permission for LA04/2025/1896/F, amending the former Belfast Metropolitan College Whiterock Road scheme to 77 social housing units and a children's centre.",
    observed_change: "Committee approval was recorded for 77 social housing units, a children's centre, car parking, landscaping, open space, access works, and a substation.",
    area: "Former Belfast Metropolitan College Campus, Whiterock Road",
    latitude: 54.588,
    longitude: -5.973,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 17 February 2026",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?MId=12348",
    source_record_id: "LA04/2025/1896/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "social housing and children's centre",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Planning permission is an approval milestone, not evidence that construction started or completed. It amends a prior permission."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_lagan_gateway_phase2_greenway_approved_2025",
    date: "2025-06-17",
    bucket: "planning/development/architecture/public-realm",
    title: "Lagan Gateway Phase 2 greenway connection was approved",
    summary: "Belfast Planning Committee granted planning permission for LA04/2024/1036/F, a Lagan Gateway Phase 2 greenway connection from Annadale Embankment toward Belvoir Forest Park.",
    observed_change: "Committee approval was recorded for compacted gravel paths, greenway connection works, and associated landscape/site works.",
    area: "Annadale Embankment to Belvoir Forest Park",
    latitude: 54.553,
    longitude: -5.928,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 17 June 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=12047&Ver=4",
    source_record_id: "LA04/2024/1036/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "greenway and public realm connection",
    geometry_source: "Approximate midpoint geocoded from committee route description",
    geometry_precision: "corridor midpoint",
    limitations: "Planning permission is an approval milestone and the point is a route midpoint, not the full greenway geometry."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_carnanmore_park_3g_pitch_approved_2025",
    date: "2025-03-18",
    bucket: "planning/development/architecture/sport",
    title: "60 Carnanmore Park 3G football pitch was approved",
    summary: "Belfast Planning Committee approved LA04/2024/1281/F for construction of a new 3G football pitch on existing grass pitches at 60 Carnanmore Park.",
    observed_change: "Committee approval was recorded for a new all-weather 3G football pitch and associated site works.",
    area: "60 Carnanmore Park",
    latitude: 54.579,
    longitude: -5.963,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 18 March 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=12040",
    source_record_id: "LA04/2024/1281/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "sports pitch and site works",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Planning permission is an approval milestone, not evidence that construction started or completed."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_rory_gallagher_statue_approved_2024",
    date: "2024-12-10",
    bucket: "planning/development/architecture/public-art",
    title: "Rory Gallagher statue at Ulster Hall was approved",
    summary: "Belfast Planning Committee granted planning permission for LA04/2024/2016/F, a life-sized Rory Gallagher statue on the patio area beside Ulster Hall.",
    observed_change: "Committee approval was recorded for a life-sized statue beside Ulster Hall at 30 Bedford Street.",
    area: "Ulster Hall, 30 Bedford Street",
    latitude: 54.5944,
    longitude: -5.9309,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 10 December 2024",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?MId=11931",
    source_record_id: "LA04/2024/2016/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "public art / statue",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Planning permission is an approval milestone, not evidence that the statue was installed."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_ulidia_primary_school_renewal_approved_2024",
    date: "2024-12-10",
    bucket: "planning/development/architecture/education",
    title: "Ulidia Primary School renewal was approved",
    summary: "Belfast Planning Committee granted renewal of LA04/2018/1755/F for a new seven-classroom primary school and single-unit nursery at the Ulidia Resource Centre, Somerset Street.",
    observed_change: "Committee approval was recorded for renewal of planning permission for a primary school, nursery, car/bus parking, drop-off, footpaths, boundaries, and play areas.",
    area: "Ulidia Resource Centre, Somerset Street",
    latitude: 54.605,
    longitude: -5.884,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 10 December 2024",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?MId=11931",
    source_record_id: "LA04/2024/0475/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "primary school and nursery",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Record captures renewal of planning permission, not initial approval or construction completion."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_fortwilliam_park_sheltered_housing_approved_2025",
    date: "2025-05-13",
    bucket: "planning/development/architecture/housing",
    title: "68 Fortwilliam Park sheltered housing was approved",
    summary: "Belfast Planning Committee approved LA04/2024/0058/F, replacing a 31-bed private nursing home at 68 Fortwilliam Park with 20 sheltered housing units and associated facilities.",
    observed_change: "Committee approval was recorded for demolition of the former nursing home and erection of a three-storey sheltered housing building with communal facilities, landscaping, parking, and site works.",
    area: "68 Fortwilliam Park",
    latitude: 54.6308,
    longitude: -5.9321,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 13 May 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=12045",
    source_record_id: "LA04/2024/0058/F",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "sheltered housing",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Planning permission is an approval milestone, not evidence that demolition or construction started."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_ann_street_hotel_facade_alterations_approved_2025",
    date: "2025-12-09",
    bucket: "planning/development/architecture/hotel",
    title: "10-22 Ann Street hotel and facade alterations were approved",
    summary: "Belfast Planning Committee granted planning permission and demolition consent for LA04/2025/0556/F and LA04/2025/0557/DCA at 10-22 Ann Street, including hotel use and external facade alterations.",
    observed_change: "Committee approval was recorded for change of use to public house, restaurants, hotel, retail, two additional hotel storeys, and external facade alterations.",
    area: "10-22 Ann Street, Crown Entry",
    latitude: 54.5999,
    longitude: -5.9259,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 9 December 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?MId=12340",
    source_record_id: "LA04/2025/0556/F; LA04/2025/0557/DCA",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "hotel conversion and facade alterations",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Planning permission and demolition consent are approval milestones, not evidence that works started or completed."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_kings_hall_plot8_car_park_public_realm_approved_2025",
    date: "2025-05-13",
    bucket: "planning/development/architecture/mixed-use",
    title: "King's Hall Plot 8 car park and public realm reserved matters were approved",
    summary: "Belfast Planning Committee approved LA04/2024/2026/RM for a multi-storey car park with ground-floor local retail, restaurant, cafe, leisure, gym, public realm, and central plaza at the King's Hall site.",
    observed_change: "Committee approval was recorded for reserved matters covering layout, scale, appearance, landscaping, ground-floor uses, and public realm/open-space elements at Plot 8.",
    area: "Royal Ulster Agricultural Society, King's Hall, 488-516 Lisburn Road",
    latitude: 54.5626,
    longitude: -5.9785,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 13 May 2025",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=12045",
    source_record_id: "LA04/2024/2026/RM",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Not specified by source",
    project_type: "multi-storey car park, ground-floor uses, and public realm",
    geometry_source: "Approximate point geocoded from committee location text",
    geometry_precision: "site",
    limitations: "Reserved matters approval refines an existing outline permission and is not evidence that construction started or completed."
  }
];

const existing = new Set(doc.events.map((event) => event.event_id));
const duplicate = records.find((event) => existing.has(event.event_id));
if (duplicate) {
  throw new Error(`Duplicate event_id: ${duplicate.event_id}`);
}

doc.events.push(...records);
fs.writeFileSync(path, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`appended ${records.length} architecture records`);
