const fs = require("fs");

const path = "data/manual_drops/architecture_milestones/architecture_milestones_2008_2026.json";
const doc = JSON.parse(fs.readFileSync(path, "utf8"));

const retrievedAt = "2026-05-17";

const records = [
  {
    city_id: "london",
    event_id: "lon_arch_pears_maudsley_centre_completion_2024",
    date: "2024-01-01",
    bucket: "planning/development/architecture/health and research",
    title: "Pears Maudsley Centre was listed as built",
    summary: "NLA records the Pears Maudsley Centre for Children and Young People as a built Southwark healthcare and research building, with completion in 2024.",
    observed_change: "A child and young-person mental-health care and research building was recorded as completed at the Maudsley / King's College Hospital campus.",
    area: "Pears Maudsley Centre, Denmark Hill",
    latitude: 51.4678,
    longitude: -0.0909,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Pears Maudsley Centre for Children and Young People",
    source_url: "https://www.nla.london/projects/pears-maudsley-centre-for-children-and-young-people",
    source_record_id: "nla-pears-maudsley-centre-children-young-people",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Arcadis, formerly IBI Group, with South London and Maudsley Trust, King's College London, Maudsley Charity, and project team",
    project_type: "healthcare and research building",
    geometry_source: "Approximate point geocoded from NLA-stated King's College Hospital / Denmark Hill location.",
    geometry_precision: "campus",
    limitations: "Source is a curated project page. Year-only completion is represented as the first day of the stated year; commissioning, clinical opening, and service outcomes require separate evidence."
  },
  {
    city_id: "london",
    event_id: "lon_arch_author_kings_cross_completion_2024",
    date: "2024-04-01",
    bucket: "planning/development/architecture/build-to-rent housing",
    title: "Author King's Cross was listed as built",
    summary: "NLA records Author King's Cross as a built Camden build-to-rent scheme combining 218 apartments, commercial units, leisure, amenity space, and a new London square, with completion in April 2024.",
    observed_change: "A residential-led mixed-use block with new public-realm space was recorded as completed at King's Cross.",
    area: "180 York Way, King's Cross",
    latitude: 51.5384,
    longitude: -0.1264,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Author King's Cross",
    source_url: "https://nla.london/projects/author-kings-cross",
    source_record_id: "nla-author-kings-cross",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "David Morley Architects, Feilden Clegg Bradley Studios, Haptic Architects, Fabrix, Related Argent, and project team",
    project_type: "build-to-rent housing and mixed-use public realm",
    geometry_source: "Approximate point geocoded from NLA-stated 180 York Way location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. The event records completion of the built scheme; tenancy, occupancy, affordability, and later public-space management require separate source records."
  },
  {
    city_id: "london",
    event_id: "lon_arch_unity_place_completion_2022",
    date: "2022-01-01",
    bucket: "planning/development/architecture/social housing",
    title: "Unity Place was listed as built",
    summary: "NLA records Unity Place as a built social housing project in South Kilburn, forming part of Brent Council's regeneration masterplan, with completion in 2022.",
    observed_change: "A social housing development was recorded as completed within the South Kilburn regeneration area.",
    area: "Unity Place, South Kilburn",
    latitude: 51.5333,
    longitude: -0.1956,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Unity Place",
    source_url: "https://www.nla.london/index.php/projects/unity-place-3",
    source_record_id: "nla-unity-place-3",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Alison Brooks Architects, Feilden Clegg Bradley Studios, Gort Scott, Grant Associates, Buro Happold, RM_A, and project team",
    project_type: "social housing regeneration",
    geometry_source: "Approximate point geocoded from NLA-stated Rudolph Road / South Kilburn location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Year-only completion is represented as the first day of the stated year; phasing, tenure allocation, and resident move-in require separate evidence."
  },
  {
    city_id: "london",
    event_id: "lon_arch_luma_kings_cross_completion_2020",
    date: "2020-01-01",
    bucket: "planning/development/architecture/residential",
    title: "LUMA King's Cross was listed as built",
    summary: "NLA records LUMA King's Cross as a built boutique residential building in Camden, with completion in 2020.",
    observed_change: "A residential building between King's Cross public spaces was recorded as completed.",
    area: "6 Lewis Cubitt Walk, King's Cross",
    latitude: 51.5367,
    longitude: -0.126,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: LUMA, King's Cross",
    source_url: "https://nla.london/projects/luma-kings-cross",
    source_record_id: "nla-luma-kings-cross",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA completion year",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Squire and Partners, Conran and Partners, Tom Stuart-Smith, Ramboll, Hoare Lea, Argent, and project team",
    project_type: "residential building",
    geometry_source: "Approximate point geocoded from NLA-stated 6 Lewis Cubitt Walk location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page. Year-only completion is represented as the first day of the stated year; sales, occupation, and estate-management details are not inferred."
  },
  {
    city_id: "london",
    event_id: "lon_arch_lakeside_centre_completion_2020",
    date: "2020-09-01",
    bucket: "planning/development/architecture/cultural workspace",
    title: "Lakeside Centre was listed as built",
    summary: "NLA records the Lakeside Centre in Thamesmead as a built creative hub and landmark Brutalist refurbishment, with estimated completion in September 2020.",
    observed_change: "A former lakeside community and leisure building was recorded as transformed into a creative hub with artist workspaces and associated uses.",
    area: "Lakeside Centre, Thamesmead",
    latitude: 51.5015,
    longitude: 0.1199,
    source_ids: ["london-architecture-public-pages"],
    source_name: "New London Architecture project page: Lakeside Centre",
    source_url: "https://www.nla.london/projects/lakeside-centre-1",
    source_record_id: "nla-lakeside-centre-1",
    source_retrieved_at: retrievedAt,
    source_date_field: "NLA estimated completion month",
    source_dataset_id: "london-architecture-public-pages",
    confidence: "documented",
    architect: "Architecture 00, Bow Arts, Peabody, Icon Design Partnership, PHI Structural Design, Climate Force, and project team",
    project_type: "creative hub retrofit",
    geometry_source: "Approximate point geocoded from NLA-stated Bazalgette Way / Southmere Lake location.",
    geometry_precision: "site",
    limitations: "Source is a curated project page with an estimated completion month. Public programming, live-work occupancy, and later operating changes require separate records."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_broad_channel_phase2_completion_2024",
    date: "2024-10-25",
    bucket: "planning/development/infrastructure/coastal streets",
    title: "Broad Channel Phase II street-raising project was completed",
    summary: "NYC DEP, DOT, and DDC announced completion of Phase II of the Broad Channel project in Queens, including raised streets, new storm sewers, and reconstructed bulkheads.",
    observed_change: "A coastal street and drainage infrastructure phase was recorded as completed in Broad Channel.",
    area: "Broad Channel, Queens",
    latitude: 40.606,
    longitude: -73.817,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Broad Channel Phase II",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2024/pr-102524-BroadChannelPhase2.page",
    source_record_id: "nyc-ddc-pr-102524-broad-channel-phase-2",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DOT, NYC DDC, and project team",
    project_type: "coastal street, storm sewer, and bulkhead infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated Broad Channel project area.",
    geometry_precision: "neighbourhood",
    limitations: "The event records a project phase at neighbourhood precision. It is distinct from the 2020 Phase I record and does not map individual blocks, pipes, or bulkhead segments."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_south_shore_bluebelt_projects_completion_2021",
    date: "2021-08-27",
    bucket: "planning/development/infrastructure/bluebelt",
    title: "Three Staten Island South Shore Bluebelt projects were completed",
    summary: "NYC DEP and DDC announced completion of three Bluebelt projects on Staten Island's South Shore, adding wetland stormwater infrastructure, catch basins, storm sewers, water mains, hydrants, and sanitary sewers.",
    observed_change: "A set of natural stormwater-management and utility infrastructure projects was recorded as completed in Tottenville, Eltingville, and Great Kills.",
    area: "Tottenville, Eltingville, and Great Kills",
    latitude: 40.531,
    longitude: -74.191,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: South Shore Bluebelts",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2021/pr-082721-bluebelts.page",
    source_record_id: "nyc-ddc-pr-082721-south-shore-bluebelts",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DDC, and project team",
    project_type: "Bluebelt stormwater and utility infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated South Shore Staten Island project neighbourhoods.",
    geometry_precision: "neighbourhood",
    limitations: "The event records a three-project completion milestone at neighbourhood precision. It does not map individual wetlands, sewer alignments, catch basins, or utility connections."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_hollis_queens_village_infrastructure_completion_2021",
    date: "2021-06-07",
    bucket: "planning/development/infrastructure/street and utilities",
    title: "Hollis and Queens Village sewer and street project was completed",
    summary: "NYC DEP, DOT, and DDC announced completion of a USD 20.5 million project in Hollis and Queens Village, including water mains, storm sewers, sanitary sewers, catch basins, roadway repaving, sidewalks, curb extensions, pedestrian ramps, and bus pads.",
    observed_change: "A multi-block street, drainage, sewer, water-main, sidewalk, curb-extension, ramp, and bus-pad upgrade was recorded as completed in Hollis and Queens Village.",
    area: "Hollis and Queens Village",
    latitude: 40.7102,
    longitude: -73.758,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Hollis and Queens Village infrastructure",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2021/pr-060721-Hollis.page",
    source_record_id: "nyc-ddc-pr-060721-hollis-queens-village",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DOT, NYC DDC, and project team",
    project_type: "street, sewer, water-main, and pedestrian infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated Hollis and Queens Village project area.",
    geometry_precision: "neighbourhood",
    limitations: "The event records neighbourhood-scale completion and does not map the 20 individual blocks, pipe alignments, bus pads, or curb-extension geometries."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_ninth_street_gowanus_drainage_completion_2020",
    date: "2020-02-25",
    bucket: "planning/development/infrastructure/sewer",
    title: "Ninth Street drainage upgrade in Gowanus was completed",
    summary: "NYC DEP and DDC announced completion of a sewer upgrade along Ninth Street in the Gowanus and Carroll Gardens neighborhoods of Brooklyn.",
    observed_change: "Stormwater, sanitary, combined sewer, catch-basin, and water-main works were recorded as completed along the Ninth Street project corridor.",
    area: "Ninth Street, Gowanus and Carroll Gardens",
    latitude: 40.674,
    longitude: -73.993,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "NYC Department of Design and Construction press release: Ninth Street drainage",
    source_url: "https://www.nyc.gov/site/ddc/about/press-releases/2020/pr-022720-Ninth-Street-Drainage.page",
    source_record_id: "nyc-ddc-pr-022720-ninth-street-drainage",
    source_retrieved_at: retrievedAt,
    source_date_field: "DDC press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYC DEP, NYC DDC, and project team",
    project_type: "stormwater, sanitary sewer, and water-main infrastructure",
    geometry_source: "Approximate point geocoded from DDC-stated Ninth Street / Gowanus Canal corridor.",
    geometry_precision: "corridor",
    limitations: "The event records corridor-scale completion and does not map each pipe, catch basin, or water-main segment."
  },
  {
    city_id: "nyc",
    event_id: "nyc_arch_muhlenberg_branch_reopening_2025",
    date: "2025-09-19",
    bucket: "planning/development/architecture/library renovation",
    title: "Muhlenberg Branch library reopened after renovation",
    summary: "The New York Public Library announced the grand reopening of the landmarked Muhlenberg Branch after renovation, including infrastructure upgrades, new interior finishes, exterior improvements, and accessibility works.",
    observed_change: "A century-old Chelsea library branch was recorded as reopened after building-system, accessibility, interior, and exterior renovation works.",
    area: "Muhlenberg Branch Library, Chelsea",
    latitude: 40.7445,
    longitude: -73.9974,
    source_ids: ["nyc-architecture-public-pages"],
    source_name: "New York Public Library press release: Muhlenberg Branch reopening",
    source_url: "https://www.nypl.org/press/new-york-public-library-hosts-ribbon-cutting-landmarked-muhlenberg-branch",
    source_record_id: "nypl-muhlenberg-branch-reopening-2025-09-19",
    source_retrieved_at: retrievedAt,
    source_date_field: "NYPL press release date",
    source_dataset_id: "nyc-architecture-public-pages",
    confidence: "documented",
    architect: "NYPL, NYC DDC, and project team; architect not named in source extract",
    project_type: "landmarked library renovation",
    geometry_source: "Approximate point geocoded from Muhlenberg Branch Library / Chelsea location.",
    geometry_precision: "site",
    limitations: "The event records reopening after renovation. It does not itemize each construction package or confirm long-term operating changes."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_havelock_house_housing_approved_2024",
    date: "2024-12-10",
    bucket: "planning/development/architecture/social housing",
    title: "Havelock House social housing scheme was approved",
    summary: "Belfast Planning Committee approved planning permission for 104 residential units at 1 Havelock House, Havelock Place, subject to conditions and a Section 76 planning agreement.",
    observed_change: "A documented planning decision was recorded for two residential blocks and associated landscaping, amenity space, cycle and car parking, and site works at Havelock Place.",
    area: "1 Havelock House, Havelock Place",
    latitude: 54.5904,
    longitude: -5.923,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 10 December 2024",
    source_url: "https://minutes.belfastcity.gov.uk/mgAi.aspx?ID=81233",
    source_record_id: "bcc-planning-2024-12-10-havelock-house-la04-2024-0626",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant team named in minutes; design team not otherwise specified in extracted minutes",
    project_type: "social housing planning approval",
    geometry_source: "Approximate point geocoded from committee-stated Havelock House / Havelock Place location.",
    geometry_precision: "site",
    limitations: "The event records committee approval subject to conditions and a planning agreement. It does not confirm decision notice issue, construction start, tenure delivery, or occupation."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_parkmore_building_childcare_approved_2024",
    date: "2024-06-27",
    bucket: "planning/development/architecture/childcare",
    title: "Parkmore Building childcare change of use was approved",
    summary: "Belfast Planning Committee granted temporary planning permission for change of use of the former Parkmore Building at 284A Ormeau Road from offices to a special-needs childcare facility.",
    observed_change: "A documented planning approval was recorded for a childcare use in an existing Ormeau Road building, with associated parking and access works.",
    area: "Parkmore Building, 284A Ormeau Road",
    latitude: 54.5778,
    longitude: -5.9139,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 27 June 2024",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=11809",
    source_record_id: "bcc-planning-2024-06-27-parkmore-building-la04-2024-0102",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "temporary childcare change-of-use approval",
    geometry_source: "Approximate point geocoded from committee-stated 284A Ormeau Road location.",
    geometry_precision: "site",
    limitations: "The event records a temporary change-of-use approval for an existing building. Fit-out, opening, service operation, and the end of the temporary permission require separate evidence."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_donegall_quay_mixed_use_approved_2024",
    date: "2024-06-27",
    bucket: "planning/development/architecture/mixed-use office",
    title: "Donegall Quay mixed-use office building was approved",
    summary: "Belfast Planning Committee granted planning permission for a 5- to 10-storey building west of Donegall Quay with office, retail, community, cultural, restaurant, terrace, landscaping, servicing, and public-realm works.",
    observed_change: "A documented planning approval was recorded for an office-led mixed-use building and associated public-realm improvements near Belfast Harbour Office.",
    area: "Donegall Quay / Corporation Square",
    latitude: 54.6039,
    longitude: -5.9189,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 27 June 2024",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=11809",
    source_record_id: "bcc-planning-2024-06-27-donegall-quay-la04-2023-4613",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Belfast Harbour applicant-side team named in minutes; architect not otherwise specified in extracted minutes",
    project_type: "office-led mixed-use planning approval",
    geometry_source: "Approximate point geocoded from committee-stated Donegall Quay / Corporation Square location.",
    geometry_precision: "site",
    limitations: "The event records committee approval subject to conditions and a planning agreement. It does not confirm issue of the decision notice, construction start, tenants, or completion."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_belfast_telegraph_complex_renewal_approved_2024",
    date: "2024-06-27",
    bucket: "planning/development/architecture/conservation mixed-use",
    title: "Belfast Telegraph complex redevelopment permission was renewed",
    summary: "Belfast Planning Committee granted renewed full planning permission and listed building consent for the former Belfast Telegraph complex at Royal Avenue and Little Donegall Street.",
    observed_change: "A documented planning and listed-building consent decision was recorded for office-led mixed-use redevelopment with Seaver building facade restoration and related works.",
    area: "Former Belfast Telegraph complex, Royal Avenue",
    latitude: 54.6018,
    longitude: -5.9294,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 27 June 2024",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=11809",
    source_record_id: "bcc-planning-2024-06-27-belfast-telegraph-complex-la04-2024-0190-la04-2024-0203",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Turley named in minutes as applicant-side representative; architect not otherwise specified in extracted minutes",
    project_type: "planning renewal and listed-building consent",
    geometry_source: "Approximate point geocoded from committee-stated Royal Avenue / Little Donegall Street location.",
    geometry_precision: "site",
    limitations: "The event records renewal of planning permission and listed-building consent, not physical works. Construction start, demolition, facade works, and completion require separate evidence."
  },
  {
    city_id: "belfast",
    event_id: "bfs_arch_meadowhill_glen_road_housing_approved_2024",
    date: "2024-06-27",
    bucket: "planning/development/architecture/housing",
    title: "Meadowhill and Glen Road 260-dwelling scheme was approved",
    summary: "Belfast Planning Committee granted planning permission for 260 dwellings, a children's play area, and associated ancillary works on lands east of Meadowhill and around Glencolin and Glen Road.",
    observed_change: "A documented planning approval was recorded for a large residential scheme with open-space, landscaping, access, drainage, and associated site works.",
    area: "Lands east of Meadowhill and Glen Road Rise",
    latitude: 54.5751,
    longitude: -6.0151,
    source_ids: ["belfast-architecture-public-pages"],
    source_name: "Belfast City Council Planning Committee minutes: 27 June 2024",
    source_url: "https://minutes.belfastcity.gov.uk/ieListDocuments.aspx?CId=167&MId=11809",
    source_record_id: "bcc-planning-2024-06-27-meadowhill-glen-road-la04-2023-2557",
    source_retrieved_at: retrievedAt,
    source_date_field: "Planning Committee meeting date",
    source_dataset_id: "belfast-architecture-public-pages",
    confidence: "documented",
    architect: "Applicant and design team not named in minutes extract",
    project_type: "residential planning approval",
    geometry_source: "Approximate point geocoded from committee-stated Meadowhill, Glencolin, and Glen Road Rise location.",
    geometry_precision: "site",
    limitations: "The event records committee approval subject to conditions and a planning agreement. Detailed phasing, affordable-housing delivery, construction, and occupation require later source records."
  }
];

const existingIds = new Set(doc.events.map((event) => event.event_id));
const duplicateIds = records.filter((event) => existingIds.has(event.event_id)).map((event) => event.event_id);
if (duplicateIds.length > 0) {
  throw new Error(`Duplicate event_id values: ${duplicateIds.join(", ")}`);
}

doc.events.push(...records);
doc.sources = doc.sources.map((source) => {
  if (
    source.source_id === "london-architecture-public-pages" ||
    source.source_id === "nyc-architecture-public-pages" ||
    source.source_id === "belfast-architecture-public-pages"
  ) {
    return {
      ...source,
      retrieved_at: retrievedAt
    };
  }
  return source;
});

fs.writeFileSync(path, `${JSON.stringify(doc, null, 2)}\n`);
console.log(`Appended ${records.length} records to ${path}`);
