#!/usr/bin/env python3
"""Retired builder tombstone.

The old replay-manifest builder is intentionally disabled. The active product
uses the city-atlas artifacts under web/data/city-atlas/ and the Wayback imagery
manifest generated by scripts/build_wayback_imagery_manifest.js.
"""

import sys

print(
    "This retired replay-manifest builder is disabled. "
    "Use `npm run build:manifest` for the active city-atlas imagery manifest.",
    file=sys.stderr,
)
sys.exit(1)
