const fs = require("fs");
const path = require("path");

const OUT_DIR = "tmp/subagents/round127_london_official_public_realm_projects";
const RETRIEVED_AT = "2026-05-19";

const candidates = [
  {
    city_id: "london",
    candidate_id: "round127_london_opdc_willesden_junction_public_realm_consultation_2019_11",
    title: "Willesden Junction Station public-realm consultation opened",
    summary: "The OPDC consultation page records consultation on public-realm improvements around Willesden Junction Station in November-December 2019.",
    observed_change: "OPDC published a public consultation milestone for station-adjacent public-realm proposals; no construction or completion is claimed.",
    effective_date: "2019-11",
    date_precision: "month",
    bucket: "planning/development/architecture/public_realm",
    area: "Willesden Junction Station, Old Oak and Park Royal",
    latitude: 51.532,
    longitude: -0.244,
    source_id: "opdc-public-realm-project-pages",
    source_ids: ["opdc-public-realm-project-pages"],
    source_name: "OPDC Willesden Junction Station public realm consultation",
    publisher: "Old Oak and Park Royal Development Corporation / Greater London Authority",
    source_url: "https://www.london.gov.uk/who-we-are/city-halls-partners/old-oak-and-park-royal-development-corporation-opdc/opdc-consultations/Willesden-Junction-Station-public-realm-consultation",
    source_record_id: "opdc-willesden-junction-public-realm-consultation-2019-11",
    source_type: "official mayoral development corporation consultation page",
    accessed_at: RETRIEVED_AT,
    source_date_field: "consultation period stated on OPDC page",
    confidence: "documented",
    architect: "Source record does not name a project architect.",
    project_type: "station-adjacent public realm consultation",
    geometry_source: "Approximate point placed at Willesden Junction Station for atlas review.",
    geometry_precision: "approximate station/public-realm point, not a red-line boundary or works footprint",
    license_or_terms_note: "London.gov.uk terms apply; factual milestone metadata and source URL retained.",
    attribution: "Old Oak and Park Royal Development Corporation / Greater London Authority",
    limitations: "This is a consultation-stage milestone. It does not document construction start, completion, opening, usage, safety effects, regeneration effects, or causal outcomes."
  },
  {
    city_id: "london",
    candidate_id: "round127_london_opdc_willesden_old_oak_public_realm_construction_approval_2021_11_29",
    title: "OPDC approved construction-stage spend for Willesden Junction and Old Oak Lane public realm",
    summary: "OPDC decision CD172 records approval for construction activity for Willesden Junction Station public realm and Old Oak Lane towpath public realm works.",
    observed_change: "The decision records an authority-to-spend and construction-stage governance milestone for OPDC public-realm works.",
    effective_date: "2021-11-29",
    date_precision: "day",
    bucket: "planning/development/architecture/public_realm",
    area: "Willesden Junction Station and Old Oak Lane towpath",
    latitude: 51.526,
    longitude: -0.253,
    source_id: "opdc-public-realm-project-pages",
    source_ids: ["opdc-public-realm-project-pages"],
    source_name: "OPDC decision CD172",
    publisher: "Old Oak and Park Royal Development Corporation / Greater London Authority",
    source_url: "https://www.london.gov.uk/who-we-are/city-halls-partners/old-oak-and-park-royal-development-corporation-opdc/decisions/62941",
    source_record_id: "OPDC CD172 signed 2021-11-29",
    source_type: "official mayoral development corporation decision record",
    accessed_at: RETRIEVED_AT,
    source_date_field: "decision signed date",
    confidence: "documented",
    architect: "Source record does not name a project architect.",
    project_type: "public-realm construction-stage approval",
    geometry_source: "Approximate midpoint between Willesden Junction Station and Old Oak Lane towpath public-realm locations.",
    geometry_precision: "approximate corridor review point, not a red-line boundary or works footprint",
    license_or_terms_note: "London.gov.uk terms apply; factual milestone metadata and source URL retained.",
    attribution: "Old Oak and Park Royal Development Corporation / Greater London Authority",
    limitations: "This is a governance/spend approval milestone. It does not by itself document practical completion, opening, usage, safety effects, regeneration effects, or causal outcomes."
  },
  {
    city_id: "london",
    candidate_id: "round127_london_opdc_harlesden_canalside_public_realm_plans_2020_07_22",
    title: "OPDC announced Harlesden Canalside public-realm plans",
    summary: "The OPDC press page records plans to transform Harlesden Canalside along the Grand Union Canal between Acton Lane and Steele Road.",
    observed_change: "OPDC published a proposal/planning milestone for Harlesden Canalside public realm; no delivery is claimed.",
    effective_date: "2020-07-22",
    date_precision: "day",
    bucket: "planning/development/architecture/public_realm",
    area: "Harlesden Canalside, Acton Lane to Steele Road",
    latitude: 51.536,
    longitude: -0.254,
    source_id: "opdc-public-realm-project-pages",
    source_ids: ["opdc-public-realm-project-pages"],
    source_name: "OPDC Harlesden Canalside plans press page",
    publisher: "Old Oak and Park Royal Development Corporation / Greater London Authority",
    source_url: "https://www.london.gov.uk/who-we-are/city-halls-partners/old-oak-and-park-royal-development-corporation-opdc/about-us/press-releases/opdc-announce-plans-transform-harlesden-canalside",
    source_record_id: "opdc-harlesden-canalside-plans-2020-07-22",
    source_type: "official mayoral development corporation press page",
    accessed_at: RETRIEVED_AT,
    source_date_field: "press page publication date",
    confidence: "documented",
    architect: "Source record does not name a project architect.",
    project_type: "canalside public-realm proposal",
    geometry_source: "Approximate point on the Harlesden Canalside corridor for atlas review.",
    geometry_precision: "approximate corridor point, not a red-line boundary or works footprint",
    license_or_terms_note: "London.gov.uk terms apply; factual milestone metadata and source URL retained.",
    attribution: "Old Oak and Park Royal Development Corporation / Greater London Authority",
    limitations: "This is a proposal-stage public-realm milestone. It does not document construction start, completion, opening, usage, safety effects, regeneration effects, or causal outcomes."
  },
  {
    city_id: "london",
    candidate_id: "round127_london_city_st_pauls_gyratory_works_started_2025_04_28",
    title: "St Paul's Gyratory transformation works started",
    summary: "The City of London project page records a 28 April 2025 start for works on the St Paul's Gyratory transformation project.",
    observed_change: "The City of London source records a works-start milestone for public-realm and street-space transformation around St Paul's Gyratory.",
    effective_date: "2025-04-28",
    date_precision: "day",
    bucket: "planning/development/architecture/public_realm",
    area: "St Paul's Gyratory, City of London",
    latitude: 51.515,
    longitude: -0.1,
    source_id: "city-of-london-public-realm-project-pages",
    source_ids: ["city-of-london-public-realm-project-pages"],
    source_name: "City of London St Paul's Gyratory transformation project page",
    publisher: "City of London Corporation",
    source_url: "https://www.cityoflondon.gov.uk/services/streets/projects-and-proposals/st-pauls-gyratory-transformation-project",
    source_record_id: "city-of-london-st-pauls-gyratory-works-started-2025-04-28",
    source_type: "official local authority project page",
    accessed_at: RETRIEVED_AT,
    source_date_field: "project page works-start date",
    confidence: "documented",
    architect: "Source record does not name a project architect.",
    project_type: "street-space and public-realm transformation works-start milestone",
    geometry_source: "Approximate point at St Paul's Gyratory for atlas review.",
    geometry_precision: "approximate public-realm point, not a measured works footprint",
    license_or_terms_note: "City of London Corporation website terms apply; factual milestone metadata and source URL retained.",
    attribution: "City of London Corporation",
    limitations: "This is a works-start milestone. It does not document completion, opening, usage, safety effects, traffic effects, regeneration effects, or causal outcomes."
  },
  {
    city_id: "london",
    candidate_id: "round127_london_city_barbican_podium_phase2_consent_2023_06_27",
    title: "Barbican Podium phase two works received planning consent",
    summary: "The City of London press page records planning consent for the second phase of works to the Barbican Podium.",
    observed_change: "The source records a planning-consent milestone for public-realm/podium works at the Barbican estate.",
    effective_date: "2023-06-27",
    date_precision: "day",
    bucket: "planning/development/architecture/public_realm",
    area: "Barbican Podium, City of London",
    latitude: 51.52,
    longitude: -0.094,
    source_id: "city-of-london-public-realm-project-pages",
    source_ids: ["city-of-london-public-realm-project-pages"],
    source_name: "City of London Barbican Podium phase two consent press page",
    publisher: "City of London Corporation",
    source_url: "https://news.cityoflondon.gov.uk/city-of-london-corporation-achieves-planning-consent-for-the-second-phase-of-works-to-the-barbican-podium/",
    source_record_id: "city-of-london-barbican-podium-phase-two-consent-2023-06-27",
    source_type: "official local authority press page",
    accessed_at: RETRIEVED_AT,
    source_date_field: "press page publication date",
    confidence: "documented",
    architect: "Source record does not name a project architect.",
    project_type: "podium/public-realm planning-consent milestone",
    geometry_source: "Approximate point at Barbican Podium for atlas review.",
    geometry_precision: "approximate podium/public-realm point, not a measured works footprint",
    license_or_terms_note: "City of London Corporation website terms apply; factual milestone metadata and source URL retained.",
    attribution: "City of London Corporation",
    limitations: "Planning consent is an administrative milestone. It does not document construction start, completion, opening, usage, safety effects, regeneration effects, or causal outcomes."
  },
  {
    city_id: "london",
    candidate_id: "round127_london_camden_gower_bloomsbury_street_change_2021_03_01",
    title: "Gower Street and Bloomsbury Street traffic/public-realm change went live",
    summary: "Camden's West End Project update records Gower Street returning to two-way traffic and Bloomsbury Street becoming one-way in late February/early March 2021.",
    observed_change: "The council project update records a public-realm/street-operation milestone within the West End Project area.",
    effective_date: "2021-03-01",
    date_precision: "day",
    bucket: "planning/development/architecture/public_realm",
    area: "Gower Street and Bloomsbury Street, Camden",
    latitude: 51.52,
    longitude: -0.131,
    source_id: "camden-west-end-project-pages",
    source_ids: ["camden-west-end-project-pages"],
    source_name: "Camden West End Project update archive",
    publisher: "London Borough of Camden",
    source_url: "https://www3.camden.gov.uk/westendproject/2021/02/",
    source_record_id: "camden-west-end-project-gower-bloomsbury-street-change-2021-03-01",
    source_type: "official local authority project update",
    accessed_at: RETRIEVED_AT,
    source_date_field: "project update stated implementation date",
    confidence: "documented",
    architect: "Source record does not name a project architect.",
    project_type: "street/public-realm implementation milestone",
    geometry_source: "Approximate point between Gower Street and Bloomsbury Street for atlas review.",
    geometry_precision: "approximate street-corridor point, not a measured works footprint",
    license_or_terms_note: "Camden Council website terms apply; factual milestone metadata and source URL retained.",
    attribution: "London Borough of Camden",
    limitations: "This records an implementation milestone for street-space operation and public realm. It does not document broader traffic, safety, economic, usage, or causal outcomes."
  },
  {
    city_id: "london",
    candidate_id: "round127_london_westminster_church_street_green_spine_phase1_2022_08",
    title: "Church Street Green Spine phase one was recorded in Westminster AMR",
    summary: "Westminster's 2022-23 authority monitoring report records Church Street Green Spine phase one as an August 2022 public-realm milestone.",
    observed_change: "The AMR records a phase-one public-realm milestone for Church Street Green Spine.",
    effective_date: "2022-08",
    date_precision: "month",
    bucket: "planning/development/architecture/public_realm",
    area: "Church Street, Westminster",
    latitude: 51.523,
    longitude: -0.172,
    source_id: "westminster-authority-monitoring-public-realm",
    source_ids: ["westminster-authority-monitoring-public-realm"],
    source_name: "Westminster City Plan Progress Report / Authority Monitoring Report 2022-23",
    publisher: "Westminster City Council",
    source_url: "https://www.westminster.gov.uk/media/document/city-plan-progress-report---an-authority-monitoring-report-2022-23",
    source_record_id: "westminster-amr-2022-23-church-street-green-spine-phase-one-2022-08",
    source_type: "official local authority monitoring report",
    accessed_at: RETRIEVED_AT,
    source_date_field: "AMR project/milestone table month",
    confidence: "documented",
    architect: "Source record does not name a project architect.",
    project_type: "public-realm phase milestone",
    geometry_source: "Approximate point on Church Street for atlas review.",
    geometry_precision: "approximate street/public-realm point, not a measured phase boundary",
    license_or_terms_note: "Westminster City Council website terms apply; factual milestone metadata and source URL retained.",
    attribution: "Westminster City Council",
    limitations: "The AMR is a monitoring/reporting source and the candidate uses month precision. It does not document detailed as-built boundaries, usage, safety effects, regeneration effects, or causal outcomes."
  }
];

const sources = [
  {
    source_id: "opdc-public-realm-project-pages",
    source_name: "OPDC public-realm consultation, decision and press pages",
    publisher: "Old Oak and Park Royal Development Corporation / Greater London Authority",
    source_url: "https://www.london.gov.uk/who-we-are/city-halls-partners/old-oak-and-park-royal-development-corporation-opdc",
    source_type: "official mayoral development corporation web pages",
    accessed_at: RETRIEVED_AT,
    license_or_terms_note: "London.gov.uk terms apply; store factual milestone metadata and source URLs only.",
    coverage_years: "2019-2021 candidate milestones in this pack.",
    update_frequency: "Project and decision pages update irregularly.",
    geographic_scope: "Old Oak and Park Royal Development Corporation area.",
    geometry_fields: "No reusable GIS geometry observed; candidate points are approximate project review points.",
    reliability: "strong for publication/decision milestones; weak for precise works boundaries.",
    required_caveats: ["Use consultation, decision, proposal, and works-stage language exactly; do not infer delivery or outcomes."],
    ingestion_recommendation: "Use as public-realm planning/governance milestones with approximate point geometry."
  },
  {
    source_id: "city-of-london-public-realm-project-pages",
    source_name: "City of London public-realm project and press pages",
    publisher: "City of London Corporation",
    source_url: "https://www.cityoflondon.gov.uk/services/streets/projects-and-proposals",
    source_type: "official local authority project/press pages",
    accessed_at: RETRIEVED_AT,
    license_or_terms_note: "City of London Corporation website terms apply; store factual milestone metadata and source URLs only.",
    coverage_years: "2023-2025 candidate milestones in this pack.",
    update_frequency: "Project and press pages update irregularly.",
    geographic_scope: "City of London public-realm projects.",
    geometry_fields: "No reusable GIS geometry observed; candidate points are approximate project review points.",
    reliability: "strong for stated planning-consent and works-start milestones; weak for precise works boundaries.",
    required_caveats: ["Planning consent and works-start milestones do not document completion or outcomes."],
    ingestion_recommendation: "Use as public-realm administrative or works-start milestones with exact caveats."
  },
  {
    source_id: "camden-west-end-project-pages",
    source_name: "Camden West End Project pages",
    publisher: "London Borough of Camden",
    source_url: "https://www3.camden.gov.uk/westendproject/",
    source_type: "official local authority project pages",
    accessed_at: RETRIEVED_AT,
    license_or_terms_note: "Camden Council website terms apply; store factual milestone metadata and source URLs only.",
    coverage_years: "2021 candidate milestone in this pack.",
    update_frequency: "Project archive pages update irregularly.",
    geographic_scope: "Camden West End Project area.",
    geometry_fields: "No reusable GIS geometry observed; candidate points are approximate street-corridor review points.",
    reliability: "strong for stated implementation dates; weak for precise works boundaries.",
    required_caveats: ["Street-operation milestones do not document broader outcomes."],
    ingestion_recommendation: "Use as street/public-realm implementation milestones with approximate point geometry."
  },
  {
    source_id: "westminster-authority-monitoring-public-realm",
    source_name: "Westminster City Plan Progress Report / Authority Monitoring Report 2022-23",
    publisher: "Westminster City Council",
    source_url: "https://www.westminster.gov.uk/media/document/city-plan-progress-report---an-authority-monitoring-report-2022-23",
    source_type: "official local authority monitoring report",
    accessed_at: RETRIEVED_AT,
    license_or_terms_note: "Westminster City Council website terms apply; store factual milestone metadata and source URLs only.",
    coverage_years: "2022 candidate milestone in this pack.",
    update_frequency: "Annual monitoring report.",
    geographic_scope: "Westminster public-realm monitoring records.",
    geometry_fields: "Report text and project labels; candidate point is approximate.",
    reliability: "strong for monitoring-record existence and month-level milestone; weak for detailed as-built boundaries.",
    required_caveats: ["AMR milestone rows are not detailed construction records and do not document outcomes."],
    ingestion_recommendation: "Use as month-precision public-realm monitoring milestones."
  }
];

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(path.join(OUT_DIR, "candidates.json"), `${JSON.stringify({
  schema_version: "round127.london_official_public_realm_projects.v1",
  created_at: RETRIEVED_AT,
  accessed_at: RETRIEVED_AT,
  scope: "Additional London official borough/corporation public-realm and project milestones found by subagent research and duplicate-screened against existing named events.",
  candidate_count: candidates.length,
  candidates
}, null, 2)}\n`);

fs.writeFileSync(path.join(OUT_DIR, "source_audit.json"), `${JSON.stringify({
  schema_version: "round127.london_official_public_realm_projects.source_audit.v1",
  created_at: RETRIEVED_AT,
  sources
}, null, 2)}\n`);

fs.writeFileSync(path.join(OUT_DIR, "notes.md"), [
  "# Round 127 London Official Public-Realm Projects",
  "",
  "Static candidate pack derived from the London subagent's official-source findings.",
  "Events are consultation, decision, works-start, consent, implementation, or monitoring milestones only."
].join("\n"));

console.log(JSON.stringify({ candidates: candidates.length, sources: sources.length, outDir: OUT_DIR }, null, 2));
