import importlib.util
import json
import sys
from collections import Counter
from pathlib import Path


sys.dont_write_bytecode = True

ACCESSED_AT = "2026-05-19"
SOURCE_ID = "london-development-database-archive"
TASK_ID = "round148_london_ldd_archive_next5_candidates"
SCRIPT_PATH = "scripts/fetch_round148_london_ldd_archive_next5_candidates.py"
OUT_DIR = Path("tmp/subagents/round148_london_ldd_archive_next5")
OUT_PATH = OUT_DIR / "candidates.json"
SOURCE_AUDIT_PATH = OUT_DIR / "source_audit.json"
NOTES_PATH = OUT_DIR / "notes.md"
PREVIOUS_ROUND124_PATH = Path("tmp/subagents/round124_london_ldd_archive_completions/candidates.json")
PREVIOUS_ROUND132_PATH = Path("tmp/subagents/round132_london_ldd_archive_next/candidates.json")
PREVIOUS_ROUND135_PATH = Path("tmp/subagents/round135_london_ldd_archive_next2/candidates.json")
PREVIOUS_ROUND144_PATH = Path("tmp/subagents/round144_london_ldd_archive_next3/candidates.json")
PREVIOUS_ROUND146_PATH = Path("tmp/subagents/round146_london_ldd_archive_next4/candidates.json")
CANDIDATE_LIMIT = 1000

BASE_SCRIPT_PATH = Path("scripts/fetch_round144_london_ldd_archive_next3_candidates.py")


def load_base_module():
    spec = importlib.util.spec_from_file_location("round144_ldd_base", BASE_SCRIPT_PATH)
    if not spec or not spec.loader:
        raise RuntimeError(f"Could not load base LDD helper script at {BASE_SCRIPT_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


base = load_base_module()


def configure_base_globals():
    base.ACCESSED_AT = ACCESSED_AT
    base.TASK_ID = TASK_ID
    base.SCRIPT_PATH = SCRIPT_PATH
    base.OUT_DIR = OUT_DIR
    base.OUT_PATH = OUT_PATH
    base.SOURCE_AUDIT_PATH = SOURCE_AUDIT_PATH
    base.NOTES_PATH = NOTES_PATH


def prior_pack_summary(prior_packs, dedupe):
    summary = {}
    for label, path, pack in prior_packs:
        summary[f"{label}_candidate_pack_path"] = str(path)
        summary[f"{label}_candidate_rows_seen"] = len(pack["rows"])
        summary[f"{label}_candidate_rows_now_in_manual_corpus"] = len(pack["rows"] & dedupe["rows"])
        summary[f"{label}_candidate_authority_reference_pairs_now_in_manual_corpus"] = len(pack["refs"] & dedupe["refs"])
    return summary


def prior_rejection_reason(prior_packs, excel_row, ref_key, skey, tdate_key):
    for label, _, pack in prior_packs:
        if excel_row in pack["rows"]:
            return f"previous {label} candidate workbook row not found in corpus"
        if ref_key in pack["refs"]:
            return f"previous {label} candidate authority/reference not found in corpus"
        if skey in pack["source_keys"]:
            return f"previous {label} candidate source key not found in corpus"
        if tdate_key in pack["title_dates"]:
            return f"previous {label} candidate title/date not found in corpus"
    return ""


def rewrite_round148_candidate(candidate, row, excel_row):
    authority = base.clean_text(row.get("Planning Authority"))
    borough_ref = base.clean_text(row.get("Borough Reference"))
    candidate["candidate_id"] = (
        f"lon_ldd_archive_next5_round148_row_{excel_row}_"
        f"{base.slugify(authority, 36)}_{base.slugify(borough_ref, 48)}"
    )
    candidate["transformation_method"] = (
        f"Generated by {SCRIPT_PATH}. Parsed official LDD archive XLSX "
        "workbooks with a stdlib OOXML reader; deduplicated against the manual architecture corpus by LDD workbook row, "
        "planning authority/borough reference, source URL/record id, and title/date, with fallback checks against the "
        "round124, round132, round135, round144, and round146 candidate packs; filtered to Current permission status "
        "Completed, Completed Date from 2008-01-01 through 2026-05-19, valid Greater London Easting/Northing point, "
        "and architecture/public/civic/mixed-use or large-development signal; excluded domestic/minor/admin-only rows "
        "below override thresholds; sorted by signal score then date and source row; retained all remaining eligible "
        "rows unless the result exceeds the 1000-row cap."
    )
    return candidate


def candidate_for(row, excel_row, score, flags, floorspace_refs, bedroom_refs):
    candidate = base.candidate_for(row, excel_row, score, flags, floorspace_refs, bedroom_refs)
    return rewrite_round148_candidate(candidate, row, excel_row)


def source_audit(selection_summary):
    audit = base.source_audit(selection_summary)
    audit["generated_at"] = ACCESSED_AT
    audit["task"] = TASK_ID
    return audit


def write_notes(candidate_count, summary):
    final_state_note = ""
    if candidate_count == 0:
        final_state_note = (
            "\n## Final-State Result\n\n"
            "This run found no remaining eligible LDD Completed rows after deduplicating against the current manual corpus "
            "and the prior LDD candidate packs. `candidates.json` is intentionally an empty final pack for this scan.\n"
        )
    text = f"""# Round 148 London LDD archive next5 candidates

Generated the next/final London Development Database archive candidate pack beyond already ingested LDD rows in the manual architecture corpus and the prior round124/round132/round135/round144/round146 LDD candidate packs.

- Source ID: `{SOURCE_ID}`
- Candidate output: `{OUT_PATH.as_posix()}`
- Candidate count: {candidate_count}
- Cap: {CANDIDATE_LIMIT}
- Accessed/retrieved date retained in outputs: {ACCESSED_AT}
- Input LDD planning-permissions rows scanned: {summary.get("input_rows_scanned")}
- Eligible rows after dedupe and signal filters: {summary.get("eligible_scored_rows_after_dedupe_and_signal_filters")}
- Manual-corpus LDD events seen during this run: {summary.get("manual_corpus_ldd_events_seen")}
{final_state_note}

## Dedupe

The generator excludes manual-corpus LDD records by workbook row, planning authority plus borough reference, source URL plus source record id, and candidate title/date. It also checks the prior round124, round132, round135, round144, and round146 candidate packs as fallback dedupe inputs and removes duplicate source rows and authority/reference pairs inside this final batch.

## Selection

Rows must have `Current permission status = Completed`, a `Date construction completed (Completed Date)` from 2008-01-01 through {ACCESSED_AT}, and a valid Greater London LDD Easting/Northing point. Selection then prioritizes public/civic/institutional terms, architecture/development terms, large residential/floorspace/bedroom/site-area thresholds, and named regeneration/mixed-use/public-realm signals.

Small domestic, low-score alteration/extension, and administrative-only rows are excluded unless they meet a high-signal or large-development override. This keeps the batch useful for architecture/city-change review rather than turning the LDD archive into a minor-applications export.

## Caveats

These are LDD administrative/source-defined completion-status records. The source field is not independent evidence of construction, opening, occupation, final built form, current use, outcomes, or causation. Local planning authority records should be checked before promoting a candidate into canonical event status.

## Exclusion Counts

```json
{json.dumps(summary.get("exclusion_counts", {}), indent=2)}
```
"""
    NOTES_PATH.write_text(text, encoding="utf-8")


def main():
    configure_base_globals()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    permissions_xlsx = base.ensure_file(base.PERMISSIONS_XLSX, base.PERMISSIONS_DOWNLOAD)
    floorspace_xlsx = base.ensure_file(base.FLOORSPACE_XLSX, base.FLOORSPACE_DOWNLOAD)
    bedrooms_xlsx = base.ensure_file(base.BEDROOMS_XLSX, base.BEDROOMS_DOWNLOAD)

    dedupe = base.existing_ldd_dedupe()
    prior_packs = [
        ("round124", PREVIOUS_ROUND124_PATH, base.previous_candidate_pack_dedupe(PREVIOUS_ROUND124_PATH)),
        ("round132", PREVIOUS_ROUND132_PATH, base.previous_candidate_pack_dedupe(PREVIOUS_ROUND132_PATH)),
        ("round135", PREVIOUS_ROUND135_PATH, base.previous_candidate_pack_dedupe(PREVIOUS_ROUND135_PATH)),
        ("round144", PREVIOUS_ROUND144_PATH, base.previous_candidate_pack_dedupe(PREVIOUS_ROUND144_PATH)),
        ("round146", PREVIOUS_ROUND146_PATH, base.previous_candidate_pack_dedupe(PREVIOUS_ROUND146_PATH)),
    ]
    floorspace_refs = base.related_row_index(
        floorspace_xlsx,
        base.FLOORSPACE_DOWNLOAD,
        "LDD_Permissions_Non_residential_floorspace_final.xlsx",
    )
    bedroom_refs = base.related_row_index(
        bedrooms_xlsx,
        base.BEDROOMS_DOWNLOAD,
        "LDD_Permissions_Non_residential_bedrooms_final.xlsx",
    )

    scored = []
    exclusions = Counter()
    rejected_sample = []
    seen_refs = set()
    seen_rows = set()
    seen_source_keys = set()
    seen_title_dates = set()
    total_rows = 0

    for excel_row, row in base.iter_xlsx_dict_rows(permissions_xlsx):
        total_rows += 1
        authority = base.clean_text(row.get("Planning Authority"))
        borough_ref = base.clean_text(row.get("Borough Reference"))
        completed_date = base.as_date(row.get("Date construction completed (Completed Date)"))
        current_status = base.clean_text(row.get("Current permission status")).lower()
        easting = base.number(row.get("Easting"))
        northing = base.number(row.get("Northing"))
        title_label = base.label_for(row)
        source_record_id = f"LDD planning permissions workbook row {excel_row}; planning_authority={authority}; borough_reference={borough_ref}"
        tdate_key = base.title_date_key("london", f"LDD administrative completion-status record: {title_label}", completed_date)
        ref_key = base.authority_ref_key(authority, borough_ref)
        skey = base.source_key(base.DATASET_PAGE, source_record_id)

        reason = ""
        if excel_row in dedupe["rows"]:
            reason = "existing manual-corpus LDD workbook row"
        elif ref_key in dedupe["refs"]:
            reason = "existing manual-corpus LDD authority/reference"
        elif skey in dedupe["source_keys"]:
            reason = "existing manual-corpus LDD source key"
        elif tdate_key in dedupe["title_dates"]:
            reason = "existing manual-corpus title/date"
        else:
            reason = prior_rejection_reason(prior_packs, excel_row, ref_key, skey, tdate_key)

        if not reason and (
            excel_row in seen_rows
            or ref_key in seen_refs
            or skey in seen_source_keys
            or tdate_key in seen_title_dates
        ):
            reason = "duplicate inside round148 batch scan"
        elif not reason and current_status != "completed":
            reason = "not completed status"
        elif not reason and not ("2008-01-01" <= completed_date <= ACCESSED_AT):
            reason = "missing or outside 2008-2026 completed-date window"
        elif not reason and not (
            base.LONDON_BNG["min_easting"] <= easting <= base.LONDON_BNG["max_easting"]
            and base.LONDON_BNG["min_northing"] <= northing <= base.LONDON_BNG["max_northing"]
        ):
            reason = "missing or outside Greater London LDD point range"
        elif not reason:
            score, flags = base.score_row(row)
            reason = base.should_reject_by_signal(row, score, flags)
            if not reason:
                scored.append((score, completed_date, excel_row, row, flags))
                seen_rows.add(excel_row)
                seen_refs.add(ref_key)
                seen_source_keys.add(skey)
                seen_title_dates.add(tdate_key)
                continue

        exclusions[reason] += 1
        prior_batch_reasons = {
            f"previous {label} candidate workbook row not found in corpus"
            for label, _, _ in prior_packs
        } | {
            f"previous {label} candidate authority/reference not found in corpus"
            for label, _, _ in prior_packs
        }
        if len(rejected_sample) < 300 and reason not in {
            "not completed status",
            "existing manual-corpus LDD workbook row",
            "existing manual-corpus LDD authority/reference",
        } | prior_batch_reasons:
            rejected_sample.append({
                "excel_row": excel_row,
                "reason": reason,
                "planning_authority": authority,
                "borough_reference": borough_ref,
                "completed_date": completed_date,
                "title_label": title_label,
            })

    scored.sort(key=lambda item: (-item[0], item[1], item[2]))
    candidates = [
        candidate_for(row, excel_row, score, flags, floorspace_refs, bedroom_refs)
        for score, completed_date, excel_row, row, flags in scored[:CANDIDATE_LIMIT]
    ]
    for candidate in candidates:
        base.validate_candidate(candidate)

    selection_summary = {
        "input_workbook": str(permissions_xlsx),
        "input_rows_scanned": total_rows,
        "eligible_scored_rows_after_dedupe_and_signal_filters": len(scored),
        "retained_candidates": len(candidates),
        "candidate_limit": CANDIDATE_LIMIT,
        "manual_corpus_ldd_events_seen": dedupe["source_id_count"],
        "manual_corpus_ldd_workbook_rows_seen": len(dedupe["rows"]),
        "manual_corpus_ldd_authority_reference_pairs_seen": len(dedupe["refs"]),
        **prior_pack_summary(prior_packs, dedupe),
        "dedupe_fields": [
            "source_ids/source_dataset_id/source_id == london-development-database-archive",
            "source_record_id workbook row number",
            "source_record_id planning_authority and borough_reference",
            "source_url plus source_record_id",
            "city/title/date",
            "prior round124, round132, round135, round144, and round146 candidate packs as fallback dedupe inputs if corpus ingestion is incomplete",
            "same fields inside the round148 batch scan",
        ],
        "filters": [
            "Current permission status equals Completed",
            f"Date construction completed (Completed Date) between 2008-01-01 and {ACCESSED_AT}",
            "BNG Easting/Northing present and within a broad Greater London range",
            "Architecture/public/civic/mixed-use or large-development signal",
            "Minor domestic and administrative-only rows excluded unless high-signal/large-development overrides apply",
            f"Sorted by signal score, then date and workbook row; capped at {CANDIDATE_LIMIT}",
        ],
        "exclusion_counts": dict(exclusions.most_common()),
    }

    payload = {
        "generated_at": ACCESSED_AT,
        "task": TASK_ID,
        "source_id_used": SOURCE_ID,
        "candidate_count": len(candidates),
        "max_candidates": CANDIDATE_LIMIT,
        "date_window": {
            "start": "2008-01-01",
            "end": ACCESSED_AT,
            "source_field": "Date construction completed (Completed Date)",
        },
        "accessed_at": ACCESSED_AT,
        "retrieved_at": ACCESSED_AT,
        "license": "UK Open Government Licence (OGL v3)",
        "license_url": "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/",
        "global_caveat": (
            "LDD rows are administrative/source-defined planning-development records; do not present them as "
            "independent evidence of construction, opening, occupation, completion, final built form, current use, "
            "outcomes, or causation."
        ),
        "selection_summary": selection_summary,
        "source_audits": source_audit(selection_summary)["source_audits"],
        "candidates": candidates,
        "rejected_sample": rejected_sample,
    }
    OUT_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    SOURCE_AUDIT_PATH.write_text(json.dumps(source_audit(selection_summary), indent=2) + "\n", encoding="utf-8")
    write_notes(len(candidates), selection_summary)

    print(json.dumps({
        "outPath": str(OUT_PATH),
        "sourceAuditPath": str(SOURCE_AUDIT_PATH),
        "notesPath": str(NOTES_PATH),
        "inputRowsScanned": total_rows,
        "eligibleScoredRows": len(scored),
        "candidates": len(candidates),
        "manualCorpusLddEventsSeen": dedupe["source_id_count"],
        "round124CandidateRowsSeen": len(prior_packs[0][2]["rows"]),
        "round124CandidateRowsNowInManualCorpus": len(prior_packs[0][2]["rows"] & dedupe["rows"]),
        "round132CandidateRowsSeen": len(prior_packs[1][2]["rows"]),
        "round132CandidateRowsNowInManualCorpus": len(prior_packs[1][2]["rows"] & dedupe["rows"]),
        "round135CandidateRowsSeen": len(prior_packs[2][2]["rows"]),
        "round135CandidateRowsNowInManualCorpus": len(prior_packs[2][2]["rows"] & dedupe["rows"]),
        "round144CandidateRowsSeen": len(prior_packs[3][2]["rows"]),
        "round144CandidateRowsNowInManualCorpus": len(prior_packs[3][2]["rows"] & dedupe["rows"]),
        "round146CandidateRowsSeen": len(prior_packs[4][2]["rows"]),
        "round146CandidateRowsNowInManualCorpus": len(prior_packs[4][2]["rows"] & dedupe["rows"]),
        "exclusionCounts": dict(exclusions.most_common(12)),
    }, indent=2))


if __name__ == "__main__":
    main()
